export const LEGAL_STATUS = {
  INDIVIDUAL: `INDIVIDUAL`,
  INDIVIDUAL_ENTREPRENEUR: `INDIVIDUAL_ENTREPRENEUR`,
  SOLE_TRADER: `SOLE_TRADER`,
} as const;
export type ILegalStatus = (typeof LEGAL_STATUS)[keyof typeof LEGAL_STATUS];

export const LEGAL_STATUS_LABEL = {
  [LEGAL_STATUS.INDIVIDUAL]: `Individual`,
  [LEGAL_STATUS.INDIVIDUAL_ENTREPRENEUR]: `Individual Entrepreneur`,
  [LEGAL_STATUS.SOLE_TRADER]: `Sole Trader`,
} as const;
export type ILegalStatusLabel = (typeof LEGAL_STATUS_LABEL)[keyof typeof LEGAL_STATUS_LABEL];

export const STATUS_LABEL = {
  [LEGAL_STATUS.INDIVIDUAL]: LEGAL_STATUS_LABEL[LEGAL_STATUS.INDIVIDUAL],
  [LEGAL_STATUS.INDIVIDUAL_ENTREPRENEUR]: LEGAL_STATUS_LABEL[LEGAL_STATUS.INDIVIDUAL_ENTREPRENEUR],
  [LEGAL_STATUS.SOLE_TRADER]: LEGAL_STATUS_LABEL[LEGAL_STATUS.SOLE_TRADER],
};
export const LABEL_STATUS = {
  [LEGAL_STATUS_LABEL[LEGAL_STATUS.INDIVIDUAL]]: LEGAL_STATUS.INDIVIDUAL,
  [LEGAL_STATUS_LABEL[LEGAL_STATUS.INDIVIDUAL_ENTREPRENEUR]]: LEGAL_STATUS.INDIVIDUAL_ENTREPRENEUR,
  [LEGAL_STATUS_LABEL[LEGAL_STATUS.SOLE_TRADER]]: LEGAL_STATUS.SOLE_TRADER,
};
