/**
 * Admin-only enums used in list query params (aligned with DB enums).
 */

const ADMIN_TYPE = {
  SUPER: `SUPER`,
  ADMIN: `ADMIN`,
} as const;
export type TAdminType = (typeof ADMIN_TYPE)[keyof typeof ADMIN_TYPE];
const ADMIN_TYPES = [ADMIN_TYPE.SUPER, ADMIN_TYPE.ADMIN] as const;

const LEDGER_ENTRY_TYPES = {
  USER_PAYMENT: `USER_PAYMENT`,
  USER_PAYMENT_REVERSAL: `USER_PAYMENT_REVERSAL`,
  PLATFORM_FEE: `PLATFORM_FEE`,
  PLATFORM_FEE_REVERSAL: `PLATFORM_FEE_REVERSAL`,
  USER_DEPOSIT: `USER_DEPOSIT`,
  USER_DEPOSIT_REVERSAL: `USER_DEPOSIT_REVERSAL`,
  USER_PAYOUT: `USER_PAYOUT`,
  USER_PAYOUT_REVERSAL: `USER_PAYOUT_REVERSAL`,
  INTERNAL_TRANSFER: `INTERNAL_TRANSFER`,
  CURRENCY_EXCHANGE: `CURRENCY_EXCHANGE`,
} as const;
export type TLedgerEntryType = (typeof LEDGER_ENTRY_TYPES)[keyof typeof LEDGER_ENTRY_TYPES];
const LEDGER_ENTRY_TYPE_VALUES = [
  LEDGER_ENTRY_TYPES.USER_PAYMENT,
  LEDGER_ENTRY_TYPES.USER_PAYMENT_REVERSAL,
  LEDGER_ENTRY_TYPES.PLATFORM_FEE,
  LEDGER_ENTRY_TYPES.PLATFORM_FEE_REVERSAL,
  LEDGER_ENTRY_TYPES.USER_DEPOSIT,
  LEDGER_ENTRY_TYPES.USER_DEPOSIT_REVERSAL,
  LEDGER_ENTRY_TYPES.USER_PAYOUT,
  LEDGER_ENTRY_TYPES.USER_PAYOUT_REVERSAL,
  LEDGER_ENTRY_TYPES.INTERNAL_TRANSFER,
  LEDGER_ENTRY_TYPES.CURRENCY_EXCHANGE,
] as const;

const SCHEDULED_FX_CONVERSION_STATUS = {
  PENDING: `PENDING`,
  PROCESSING: `PROCESSING`,
  EXECUTED: `EXECUTED`,
  FAILED: `FAILED`,
  CANCELLED: `CANCELLED`,
} as const;
export type TScheduledFxConversionStatus =
  (typeof SCHEDULED_FX_CONVERSION_STATUS)[keyof typeof SCHEDULED_FX_CONVERSION_STATUS];
const SCHEDULED_FX_CONVERSION_STATUSES = [
  SCHEDULED_FX_CONVERSION_STATUS.PENDING,
  SCHEDULED_FX_CONVERSION_STATUS.PROCESSING,
  SCHEDULED_FX_CONVERSION_STATUS.EXECUTED,
  SCHEDULED_FX_CONVERSION_STATUS.FAILED,
  SCHEDULED_FX_CONVERSION_STATUS.CANCELLED,
] as const;

const VERIFICATION_ACTION = {
  APPROVE: `approve`,
  REJECT: `reject`,
  MORE_INFO: `more_info`,
  FLAG: `flag`,
} as const;

export type TVerificationAction = (typeof VERIFICATION_ACTION)[keyof typeof VERIFICATION_ACTION];
export const VERIFICATION_ACTIONS = [
  VERIFICATION_ACTION.APPROVE,
  VERIFICATION_ACTION.REJECT,
  VERIFICATION_ACTION.MORE_INFO,
  VERIFICATION_ACTION.FLAG,
] as const;
