export default function ContactsLoading() {
  return (
    <div
      className="
        space-y-6
      "
    >
      <div
        className="
          flex
          items-center
          justify-between
          gap-4
        "
      >
        <div
          className="
            h-8
            w-32
            animate-pulse
            rounded-lg
            bg-slate-200
            dark:bg-slate-700
          "
        />
        <div
          className="
            h-11
            w-36
            animate-pulse
            rounded-lg
            bg-slate-200
            dark:bg-slate-700
          "
        />
      </div>

      <div
        className="
          h-11
          w-full
          animate-pulse
          rounded-lg
          bg-slate-200
          dark:bg-slate-700
        "
      />

      <div
        className="
          grid
          gap-3
          sm:grid-cols-2
        "
      >
        {[1, 2, 3, 4].map((i) => (
          <div
            key={i}
            className="
              overflow-hidden
              rounded-xl
              border
              border-slate-200
              bg-white
              shadow-sm
              dark:border-slate-700
              dark:bg-slate-800
            "
          >
            <div
              className="
                p-4
              "
            >
              <div
                className="
                  flex
                  items-center
                  gap-3
                "
              >
                <div
                  className="
                    h-10
                    w-10
                    shrink-0
                    animate-pulse
                    rounded-full
                    bg-slate-200
                    dark:bg-slate-700
                  "
                />
                <div
                  className="
                    min-w-0
                    flex-1
                    space-y-2
                  "
                >
                  <div
                    className="
                      h-5
                      w-32
                      animate-pulse
                      rounded
                      bg-slate-200
                      dark:bg-slate-700
                    "
                  />
                  <div
                    className="
                      h-4
                      w-48
                      animate-pulse
                      rounded
                      bg-slate-200
                      dark:bg-slate-700
                    "
                  />
                </div>
              </div>
            </div>

            <div
              className="
                flex
                border-t
                border-slate-200
                dark:border-slate-700
              "
            >
              <div
                className="
                  h-11
                  flex-1
                  animate-pulse
                  bg-slate-50
                  dark:bg-slate-700/30
                "
              />
              <div
                className="
                  h-11
                  flex-1
                  animate-pulse
                  border-l
                  border-slate-200
                  bg-slate-50
                  dark:border-slate-700
                  dark:bg-slate-700/30
                "
              />
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}
