import { COOKIE_KEYS } from '@remoola/api-types';

const PASSWORD_NOT_SET_YET =
  `Consumer password is not set yet. Try using a different way to log in to the app, or restore your password ` as const; //eslint-disable-line

const INVALID_CREDENTIALS = `Invalid Credentials` as const;
const ADMIN_NOT_FOUND = `Admin not found` as const;
const NOT_FOUND = `Not found` as const;
const INVALID_PASSWORD = `Invalid password` as const;
const INVALID_EMAIL = `Invalid email` as const;
const TEMPORARY_PASSWORD_LIFETIME_HOURS = 3 as const;
const DEFAULT_DUE_DATE_IN_DAYS30 = 30 as const;
const PASSWORD_RE = /(?!.* )(?=(.*[A-Z]){2,})(?=.*?[a-z])(?=.*[1-9]{1,})(?=.*?[#?!@$%^&*-]).{8,}$/;
export const ADMIN_ACCESS_TOKEN_COOKIE_KEY = COOKIE_KEYS.ADMIN_ACCESS_TOKEN;
const ADMIN_REFRESH_TOKEN_COOKIE_KEY = COOKIE_KEYS.ADMIN_REFRESH_TOKEN;
export const CONSUMER_ACCESS_TOKEN_COOKIE_KEY = COOKIE_KEYS.API_V2_CONSUMER_ACCESS_TOKEN;
const CONSUMER_REFRESH_TOKEN_COOKIE_KEY = COOKIE_KEYS.API_V2_CONSUMER_REFRESH_TOKEN;
export const GOOGLE_OAUTH_STATE_COOKIE_KEY = COOKIE_KEYS.API_V2_GOOGLE_OAUTH_STATE;
export const CSRF_TOKEN_COOKIE_KEY = COOKIE_KEYS.API_V2_CSRF_TOKEN;

export const constants = {
  INVALID_CREDENTIALS,
  ADMIN_NOT_FOUND,
  NOT_FOUND,
  INVALID_PASSWORD,
  PASSWORD_NOT_SET_YET,
  INVALID_EMAIL,
  TEMPORARY_PASSWORD_LIFETIME_HOURS,
  DEFAULT_DUE_DATE_IN_DAYS30,
  PASSWORD_RE,
  ADMIN_ACCESS_TOKEN_COOKIE_KEY,
  ADMIN_REFRESH_TOKEN_COOKIE_KEY,
  CONSUMER_ACCESS_TOKEN_COOKIE_KEY,
  CONSUMER_REFRESH_TOKEN_COOKIE_KEY,
  GOOGLE_OAUTH_STATE_COOKIE_KEY,
  CSRF_TOKEN_COOKIE_KEY,
} as const;
