export const ADMIN_V2_ENDPOINTS = {
  me: { method: `GET`, path: `/admin-v2/me`, response: `AdminV2AdminIdentity` },
  authMeSessions: {
    method: `GET`,
    path: `/admin-v2/auth/me/sessions`,
    response: `AdminV2ListAdminSessionsResponse`,
  },
  authLogin: { method: `POST`, path: `/admin-v2/auth/login`, body: `AdminV2LoginBody` },
  authRefreshAccess: { method: `POST`, path: `/admin-v2/auth/refresh-access` },
  authLogout: { method: `POST`, path: `/admin-v2/auth/logout` },
  authRevokeSession: {
    method: `POST`,
    path: `/admin-v2/auth/revoke-session`,
    body: `AdminV2RevokeAdminSessionBody`,
  },
  authAcceptInvitation: {
    method: `POST`,
    path: `/admin-v2/auth/invitations/accept`,
    body: `AdminV2TokenPasswordBody`,
  },
  authForgotPassword: {
    method: `POST`,
    path: `/admin-v2/auth/forgot-password`,
    body: `AdminV2RequestPasswordResetBody`,
  },
  authResetPassword: {
    method: `POST`,
    path: `/admin-v2/auth/password/reset`,
    body: `AdminV2TokenPasswordBody`,
  },
  overviewSummary: { method: `GET`, path: `/admin-v2/overview/summary`, response: `AdminV2OverviewSummaryResponse` },
  systemSummary: { method: `GET`, path: `/admin-v2/system/summary`, response: `AdminV2SystemSummaryResponse` },
  quickstartsList: {
    method: `GET`,
    path: `/admin-v2/quickstarts`,
    query: `AdminV2QuickstartsListQuery`,
    response: `AdminV2QuickstartsListResponse`,
  },
  quickstartsGet: {
    method: `GET`,
    path: `/admin-v2/quickstarts/:quickstartId`,
    response: `AdminV2QuickstartResolvedPreset`,
  },
  savedViewsList: {
    method: `GET`,
    path: `/admin-v2/saved-views`,
    query: `AdminV2SavedViewListQuery`,
    response: `AdminV2SavedViewsListResponse`,
  },
  savedViewsCreate: {
    method: `POST`,
    path: `/admin-v2/saved-views`,
    body: `AdminV2SavedViewCreateBody`,
    response: `AdminV2SavedViewSummary`,
  },
  savedViewsUpdate: {
    method: `PATCH`,
    path: `/admin-v2/saved-views/:savedViewId`,
    body: `AdminV2SavedViewUpdateBody`,
    response: `AdminV2SavedViewSummary`,
  },
  savedViewsDelete: {
    method: `DELETE`,
    path: `/admin-v2/saved-views/:savedViewId`,
    body: `AdminV2SavedViewDeleteBody`,
  },
  operationalAlertsList: {
    method: `GET`,
    path: `/admin-v2/operational-alerts`,
    query: `AdminV2OperationalAlertListQuery`,
    response: `AdminV2OperationalAlertsListResponse`,
  },
  operationalAlertsCreate: {
    method: `POST`,
    path: `/admin-v2/operational-alerts`,
    body: `AdminV2OperationalAlertCreateBody`,
    response: `AdminV2OperationalAlertSummary`,
  },
  operationalAlertsUpdate: {
    method: `PATCH`,
    path: `/admin-v2/operational-alerts/:operationalAlertId`,
    body: `AdminV2OperationalAlertUpdateBody`,
    response: `AdminV2OperationalAlertSummary`,
  },
  operationalAlertsDelete: {
    method: `DELETE`,
    path: `/admin-v2/operational-alerts/:operationalAlertId`,
    body: `AdminV2OperationalAlertDeleteBody`,
  },
  assignmentsClaim: {
    method: `POST`,
    path: `/admin-v2/assignments/claim`,
    body: `AdminV2AssignmentClaimBody`,
    response: `AdminV2AssignmentContextSummary`,
  },
  assignmentsRelease: {
    method: `POST`,
    path: `/admin-v2/assignments/release`,
    body: `AdminV2AssignmentReleaseBody`,
  },
  assignmentsReassign: {
    method: `POST`,
    path: `/admin-v2/assignments/reassign`,
    body: `AdminV2AssignmentReassignBody`,
  },
  consumersList: {
    method: `GET`,
    path: `/admin-v2/consumers`,
    query: `AdminV2ConsumersListQuery`,
    response: `AdminV2ConsumersListResponse`,
  },
  consumersGet: { method: `GET`, path: `/admin-v2/consumers/:id`, response: `AdminV2ConsumerCaseResponse` },
  consumersContracts: {
    method: `GET`,
    path: `/admin-v2/consumers/:id/contracts`,
    query: `AdminV2ConsumerContractsQuery`,
    response: `AdminV2ConsumerContractsResponse`,
  },
  consumersLedgerSummary: {
    method: `GET`,
    path: `/admin-v2/consumers/:id/ledger-summary`,
    response: `AdminV2ConsumerLedgerSummaryResponse`,
  },
  consumersAuthHistory: {
    method: `GET`,
    path: `/admin-v2/consumers/:id/auth-history`,
    query: `AdminV2TimelineQuery`,
    response: `AdminV2ConsumerTimelineResponse`,
  },
  consumersActionLog: {
    method: `GET`,
    path: `/admin-v2/consumers/:id/action-log`,
    query: `AdminV2TimelineQuery`,
    response: `AdminV2ConsumerTimelineResponse`,
  },
  consumersCreateNote: { method: `POST`, path: `/admin-v2/consumers/:id/notes`, body: `AdminV2CreateConsumerNoteBody` },
  consumersAddFlag: { method: `POST`, path: `/admin-v2/consumers/:id/flags`, body: `AdminV2AddConsumerFlagBody` },
  consumersRemoveFlag: {
    method: `PATCH`,
    path: `/admin-v2/consumers/:id/flags/:flagId/remove`,
    body: `AdminV2RemoveConsumerFlagBody`,
  },
  consumersForceLogout: {
    method: `POST`,
    path: `/admin-v2/consumers/:id/force-logout`,
    body: `AdminV2ForceLogoutConsumerBody`,
  },
  consumersSuspend: { method: `POST`, path: `/admin-v2/consumers/:id/suspend`, body: `AdminV2SuspendConsumerBody` },
  consumersEmailResend: {
    method: `POST`,
    path: `/admin-v2/consumers/:id/email-resend`,
    body: `AdminV2ResendConsumerEmailBody`,
  },
  verificationQueue: {
    method: `GET`,
    path: `/admin-v2/verification/queue`,
    query: `AdminV2VerificationQueueQuery`,
    response: `AdminV2VerificationQueueResponse`,
  },
  verificationGet: {
    method: `GET`,
    path: `/admin-v2/verification/:consumerId`,
    response: `AdminV2VerificationCaseResponse`,
  },
  verificationApprove: {
    method: `POST`,
    path: `/admin-v2/verification/:consumerId/approve`,
    body: `AdminV2VerificationDecisionBody`,
  },
  verificationReject: {
    method: `POST`,
    path: `/admin-v2/verification/:consumerId/reject`,
    body: `AdminV2VerificationDecisionBody`,
  },
  verificationRequestInfo: {
    method: `POST`,
    path: `/admin-v2/verification/:consumerId/request-info`,
    body: `AdminV2VerificationDecisionBody`,
  },
  verificationFlag: {
    method: `POST`,
    path: `/admin-v2/verification/:consumerId/flag`,
    body: `AdminV2VerificationDecisionBody`,
  },
  paymentsList: {
    method: `GET`,
    path: `/admin-v2/payments`,
    query: `AdminV2PaymentsListQuery`,
    response: `AdminV2PaymentsListResponse`,
  },
  paymentsOperationsQueue: {
    method: `GET`,
    path: `/admin-v2/payments/operations-queue`,
    response: `AdminV2PaymentOperationsQueueResponse`,
  },
  paymentsGet: { method: `GET`, path: `/admin-v2/payments/:id`, response: `AdminV2PaymentCaseResponse` },
  paymentsRefund: { method: `POST`, path: `/admin-v2/payments/:id/refund`, body: `AdminV2PaymentReversalBody` },
  paymentsChargeback: { method: `POST`, path: `/admin-v2/payments/:id/chargeback`, body: `AdminV2PaymentReversalBody` },
  paymentMethodsList: {
    method: `GET`,
    path: `/admin-v2/payment-methods`,
    query: `AdminV2PaymentMethodsListQuery`,
    response: `AdminV2PaymentMethodsListResponse`,
  },
  paymentMethodsGet: {
    method: `GET`,
    path: `/admin-v2/payment-methods/:id`,
    response: `AdminV2PaymentMethodCaseResponse`,
  },
  paymentMethodsDisable: {
    method: `POST`,
    path: `/admin-v2/payment-methods/:id/disable`,
    body: `AdminV2DisablePaymentMethodBody`,
  },
  paymentMethodsRemoveDefault: {
    method: `POST`,
    path: `/admin-v2/payment-methods/:id/remove-default`,
    body: `AdminV2RemoveDefaultPaymentMethodBody`,
  },
  paymentMethodsDuplicateEscalate: {
    method: `POST`,
    path: `/admin-v2/payment-methods/:id/duplicate-escalate`,
    body: `AdminV2DuplicateEscalatePaymentMethodBody`,
  },
  payoutsList: {
    method: `GET`,
    path: `/admin-v2/payouts`,
    query: `AdminV2PayoutsListQuery`,
    response: `AdminV2PayoutsListResponse`,
  },
  payoutsGet: { method: `GET`, path: `/admin-v2/payouts/:id`, response: `AdminV2PayoutCaseResponse` },
  payoutsEscalate: { method: `POST`, path: `/admin-v2/payouts/:id/escalate`, body: `AdminV2EscalatePayoutBody` },
  ledgerList: {
    method: `GET`,
    path: `/admin-v2/ledger`,
    query: `AdminV2LedgerEntriesListQuery`,
    response: `AdminV2LedgerEntriesListResponse`,
  },
  ledgerDisputes: {
    method: `GET`,
    path: `/admin-v2/ledger/disputes`,
    query: `AdminV2LedgerDisputesQuery`,
    response: `AdminV2LedgerDisputesResponse`,
  },
  ledgerGet: { method: `GET`, path: `/admin-v2/ledger/:id`, response: `AdminV2LedgerEntryCaseResponse` },
  ledgerAnomaliesSummary: {
    method: `GET`,
    path: `/admin-v2/ledger/anomalies/summary`,
    response: `AdminV2LedgerAnomalySummaryResponse`,
  },
  ledgerAnomaliesList: {
    method: `GET`,
    path: `/admin-v2/ledger/anomalies`,
    query: `AdminV2LedgerAnomaliesListQuery`,
    response: `AdminV2LedgerAnomalyListResponse`,
  },
  documentsList: {
    method: `GET`,
    path: `/admin-v2/documents`,
    query: `AdminV2DocumentsListQuery`,
    response: `AdminV2DocumentsListResponse`,
  },
  documentsTags: { method: `GET`, path: `/admin-v2/documents/tags`, response: `AdminV2DocumentTagsResponse` },
  documentsDownload: { method: `GET`, path: `/admin-v2/documents/:id/download` },
  documentsGet: { method: `GET`, path: `/admin-v2/documents/:id`, response: `AdminV2DocumentCaseResponse` },
  documentsCreateTag: { method: `POST`, path: `/admin-v2/documents/tags`, body: `AdminV2DocumentTagCreateBody` },
  documentsUpdateTag: { method: `PATCH`, path: `/admin-v2/documents/tags/:id`, body: `AdminV2DocumentTagUpdateBody` },
  documentsDeleteTag: { method: `DELETE`, path: `/admin-v2/documents/tags/:id`, body: `AdminV2DocumentTagDeleteBody` },
  documentsRetag: { method: `POST`, path: `/admin-v2/documents/:id/retag`, body: `AdminV2DocumentRetagBody` },
  documentsBulkTag: { method: `POST`, path: `/admin-v2/documents/bulk-tag`, body: `AdminV2DocumentBulkTagBody` },
  exchangeRatesList: {
    method: `GET`,
    path: `/admin-v2/exchange/rates`,
    query: `AdminV2ExchangeRatesListQuery`,
    response: `AdminV2ExchangeRatesListResponse`,
  },
  exchangeRatesGet: {
    method: `GET`,
    path: `/admin-v2/exchange/rates/:id`,
    response: `AdminV2ExchangeRateCaseResponse`,
  },
  exchangeRatesApprove: {
    method: `POST`,
    path: `/admin-v2/exchange/rates/:id/approve`,
    body: `AdminV2ApproveRateBody`,
  },
  exchangeRulesList: {
    method: `GET`,
    path: `/admin-v2/exchange/rules`,
    query: `AdminV2ExchangeRulesListQuery`,
    response: `AdminV2ExchangeRulesListResponse`,
  },
  exchangeRulesGet: {
    method: `GET`,
    path: `/admin-v2/exchange/rules/:id`,
    response: `AdminV2ExchangeRuleCaseResponse`,
  },
  exchangeRulesPause: {
    method: `POST`,
    path: `/admin-v2/exchange/rules/:id/pause`,
    body: `AdminV2VersionedMutationBody`,
  },
  exchangeRulesResume: {
    method: `POST`,
    path: `/admin-v2/exchange/rules/:id/resume`,
    body: `AdminV2VersionedMutationBody`,
  },
  exchangeRulesRunNow: {
    method: `POST`,
    path: `/admin-v2/exchange/rules/:id/run-now`,
    body: `AdminV2VersionedMutationBody`,
  },
  exchangeScheduledList: {
    method: `GET`,
    path: `/admin-v2/exchange/scheduled`,
    query: `AdminV2ExchangeScheduledListQuery`,
    response: `AdminV2ExchangeScheduledListResponse`,
  },
  exchangeScheduledGet: {
    method: `GET`,
    path: `/admin-v2/exchange/scheduled/:id`,
    response: `AdminV2ExchangeScheduledCaseResponse`,
  },
  exchangeScheduledForceExecute: {
    method: `POST`,
    path: `/admin-v2/exchange/scheduled/:id/force-execute`,
    body: `AdminV2ConfirmedVersionedMutationBody`,
  },
  exchangeScheduledCancel: {
    method: `POST`,
    path: `/admin-v2/exchange/scheduled/:id/cancel`,
    body: `AdminV2ConfirmedVersionedMutationBody`,
  },
  auditAuth: {
    method: `GET`,
    path: `/admin-v2/audit/auth`,
    query: `AdminV2AuditListQuery`,
    response: `AdminV2AuditListResponse`,
  },
  auditAdminActions: {
    method: `GET`,
    path: `/admin-v2/audit/admin-actions`,
    query: `AdminV2AuditListQuery`,
    response: `AdminV2AuditListResponse`,
  },
  auditConsumerActions: {
    method: `GET`,
    path: `/admin-v2/audit/consumer-actions`,
    query: `AdminV2AuditListQuery`,
    response: `AdminV2AuditListResponse`,
  },
  adminsList: {
    method: `GET`,
    path: `/admin-v2/admins`,
    query: `AdminV2AdminsListQuery`,
    response: `AdminV2AdminsListResponse`,
  },
  adminsGet: { method: `GET`, path: `/admin-v2/admins/:id`, response: `AdminV2AdminCaseRecordResponse` },
  adminsInvite: { method: `POST`, path: `/admin-v2/admins/invite`, body: `AdminV2InviteAdminBody` },
  adminsDeactivate: { method: `POST`, path: `/admin-v2/admins/:id/deactivate`, body: `AdminV2DeactivateAdminBody` },
  adminsRestore: { method: `POST`, path: `/admin-v2/admins/:id/restore`, body: `AdminV2VersionedMutationBody` },
  adminsRoleChange: { method: `POST`, path: `/admin-v2/admins/:id/role-change`, body: `AdminV2ChangeAdminRoleBody` },
  adminsPermissionsChange: {
    method: `POST`,
    path: `/admin-v2/admins/:id/permissions-change`,
    body: `AdminV2ChangeAdminPermissionsBody`,
  },
  adminsPasswordReset: {
    method: `POST`,
    path: `/admin-v2/admins/:id/password-reset`,
    body: `AdminV2VersionedMutationBody`,
  },
  adminsPasswordPatch: {
    method: `PATCH`,
    path: `/admin-v2/admins/:id/password`,
    body: `AdminV2AdminPasswordPatchBody`,
  },
  adminsPatch: { method: `PATCH`, path: `/admin-v2/admins/:id`, body: `AdminV2LegacyAdminStatusBody` },
  adminsSessionsList: {
    method: `GET`,
    path: `/admin-v2/admins/:id/sessions`,
    response: `AdminV2ListAdminSessionsResponse`,
  },
  adminsSessionsRevoke: { method: `POST`, path: `/admin-v2/admins/:id/sessions/:sessionId/revoke` },
} as const;

export type AdminV2EndpointKey = keyof typeof ADMIN_V2_ENDPOINTS;
export type AdminV2EndpointDefinition = (typeof ADMIN_V2_ENDPOINTS)[AdminV2EndpointKey];
