import { HELP_GUIDE_SLUG, type HelpGuideSlug } from './guide-slugs';
import {
  HELP_AUDIENCE_STATE,
  HELP_GUIDE_CATEGORY,
  HELP_GUIDE_FEATURE,
  HELP_GUIDE_TYPE,
  type HelpGuideDefinition,
  type PublicHelpGuideMeta,
} from './guide-types';

export { HELP_GUIDE_SLUG };
export type { HelpGuideSlug };

const helpGuideRegistryDefinitions = [
  {
    slug: HELP_GUIDE_SLUG.GETTING_STARTED_OVERVIEW,
    guideType: HELP_GUIDE_TYPE.OVERVIEW,
    title: `How the consumer workspace is organized`,
    summary: `Get oriented in the main workspace, understand where core tasks live, and know where to go first.`,
    category: HELP_GUIDE_CATEGORY.GETTING_STARTED,
    feature: HELP_GUIDE_FEATURE.WORKSPACE,
    audienceState: HELP_AUDIENCE_STATE.AUTHENTICATED,
    routeAffinity: [`/dashboard`, `/payments`, `/documents`, `/settings`],
    order: 10,
    prerequisites: [`Sign in to your workspace so the shell navigation and main sections are available.`],
    relatedGuides: [
      HELP_GUIDE_SLUG.DASHBOARD_OVERVIEW,
      HELP_GUIDE_SLUG.PAYMENTS_OVERVIEW,
      HELP_GUIDE_SLUG.VERIFICATION_HOW_IT_WORKS,
    ],
  },
  {
    slug: HELP_GUIDE_SLUG.DASHBOARD_OVERVIEW,
    guideType: HELP_GUIDE_TYPE.OVERVIEW,
    title: `Dashboard overview`,
    summary: `Understand what the dashboard is summarizing, how balances and tasks relate to the rest of the workspace, and where to go next.`,
    category: HELP_GUIDE_CATEGORY.DASHBOARD,
    feature: HELP_GUIDE_FEATURE.DASHBOARD,
    audienceState: HELP_AUDIENCE_STATE.AUTHENTICATED,
    routeAffinity: [`/dashboard`],
    order: 15,
    prerequisites: [
      `Sign in and open the dashboard so you can compare the guide with the current cards, panels, and verification state.`,
    ],
    relatedGuides: [
      HELP_GUIDE_SLUG.DASHBOARD_TASKS_AND_NEXT_STEPS,
      HELP_GUIDE_SLUG.DASHBOARD_COMMON_ISSUES,
      HELP_GUIDE_SLUG.GETTING_STARTED_OVERVIEW,
      HELP_GUIDE_SLUG.PAYMENTS_OVERVIEW,
      HELP_GUIDE_SLUG.VERIFICATION_HOW_IT_WORKS,
    ],
  },
  {
    slug: HELP_GUIDE_SLUG.DASHBOARD_TASKS_AND_NEXT_STEPS,
    guideType: HELP_GUIDE_TYPE.TASK,
    title: `How to use dashboard tasks and next steps`,
    summary: `Use the dashboard cards, tasks, quick documents, and payment signals to choose the right next route without guessing.`,
    category: HELP_GUIDE_CATEGORY.DASHBOARD,
    feature: HELP_GUIDE_FEATURE.DASHBOARD,
    audienceState: HELP_AUDIENCE_STATE.AUTHENTICATED,
    routeAffinity: [`/dashboard`],
    order: 16,
    prerequisites: [
      `Open the dashboard so the balance cards, task list, quick documents, and verification state are visible.`,
    ],
    relatedGuides: [
      HELP_GUIDE_SLUG.DASHBOARD_OVERVIEW,
      HELP_GUIDE_SLUG.DASHBOARD_COMMON_ISSUES,
      HELP_GUIDE_SLUG.PAYMENTS_OVERVIEW,
      HELP_GUIDE_SLUG.DOCUMENTS_OVERVIEW,
      HELP_GUIDE_SLUG.VERIFICATION_HOW_IT_WORKS,
    ],
  },
  {
    slug: HELP_GUIDE_SLUG.DASHBOARD_COMMON_ISSUES,
    guideType: HELP_GUIDE_TYPE.TROUBLESHOOTING,
    title: `Common dashboard issues and what to do next`,
    summary: `Use this guide when dashboard data looks empty, stale, or temporarily unavailable and you need to know the safest next move.`,
    category: HELP_GUIDE_CATEGORY.DASHBOARD,
    feature: HELP_GUIDE_FEATURE.DASHBOARD,
    audienceState: HELP_AUDIENCE_STATE.AUTHENTICATED,
    routeAffinity: [`/dashboard`],
    order: 18,
    prerequisites: [
      `Open the dashboard and compare the guide with the message, panel, or banner that currently looks incorrect or blocked.`,
    ],
    relatedGuides: [
      HELP_GUIDE_SLUG.DASHBOARD_OVERVIEW,
      HELP_GUIDE_SLUG.DASHBOARD_TASKS_AND_NEXT_STEPS,
      HELP_GUIDE_SLUG.PAYMENTS_OVERVIEW,
      HELP_GUIDE_SLUG.VERIFICATION_HOW_IT_WORKS,
    ],
  },
  {
    slug: HELP_GUIDE_SLUG.PAYMENTS_OVERVIEW,
    guideType: HELP_GUIDE_TYPE.OVERVIEW,
    title: `Payments overview`,
    summary: `Understand the payments area, the main actions you can take there, and which routes support each step.`,
    category: HELP_GUIDE_CATEGORY.PAYMENTS,
    feature: HELP_GUIDE_FEATURE.PAYMENTS,
    audienceState: HELP_AUDIENCE_STATE.AUTHENTICATED,
    routeAffinity: [`/payments`, `/payments/new-request`, `/payments/start`, `/payments/[paymentRequestId]`],
    order: 20,
    prerequisites: [`Open the payments area from the authenticated workspace navigation.`],
    relatedGuides: [
      HELP_GUIDE_SLUG.PAYMENTS_CREATE_REQUEST,
      HELP_GUIDE_SLUG.PAYMENTS_START_PAYMENT,
      HELP_GUIDE_SLUG.PAYMENTS_STATUSES,
      HELP_GUIDE_SLUG.PAYMENTS_COMMON_ISSUES,
    ],
  },
  {
    slug: HELP_GUIDE_SLUG.PAYMENTS_CREATE_REQUEST,
    guideType: HELP_GUIDE_TYPE.TASK,
    title: `How to create a payment request`,
    summary: `Create a payment request when you need another party to review and pay through the platform.`,
    category: HELP_GUIDE_CATEGORY.PAYMENTS,
    feature: HELP_GUIDE_FEATURE.PAYMENTS,
    audienceState: HELP_AUDIENCE_STATE.AUTHENTICATED,
    routeAffinity: [`/payments`, `/payments/new-request`],
    order: 30,
    prerequisites: [
      `Be signed in to the workspace.`,
      `Have the recipient email, amount, currency, and any due date or description ready before you start.`,
    ],
    relatedGuides: [
      HELP_GUIDE_SLUG.PAYMENTS_OVERVIEW,
      HELP_GUIDE_SLUG.DOCUMENTS_UPLOAD_AND_ATTACH,
      HELP_GUIDE_SLUG.PAYMENTS_COMMON_ISSUES,
    ],
  },
  {
    slug: HELP_GUIDE_SLUG.PAYMENTS_START_PAYMENT,
    guideType: HELP_GUIDE_TYPE.TASK,
    title: `How to start a payment`,
    summary: `Start a payer-side one-off payment, choose the settlement method, and handle unknown recipients without leaving the workspace.`,
    category: HELP_GUIDE_CATEGORY.PAYMENTS,
    feature: HELP_GUIDE_FEATURE.PAYMENTS,
    audienceState: HELP_AUDIENCE_STATE.AUTHENTICATED,
    routeAffinity: [`/payments`, `/payments/start`, `/payments/[paymentRequestId]`],
    order: 35,
    prerequisites: [
      `Be signed in to the workspace.`,
      `Have the recipient email, amount, and settlement method ready before you submit the flow.`,
    ],
    relatedGuides: [
      HELP_GUIDE_SLUG.PAYMENTS_OVERVIEW,
      HELP_GUIDE_SLUG.PAYMENTS_CREATE_REQUEST,
      HELP_GUIDE_SLUG.PAYMENTS_STATUSES,
      HELP_GUIDE_SLUG.PAYMENTS_COMMON_ISSUES,
    ],
  },
  {
    slug: HELP_GUIDE_SLUG.PAYMENTS_STATUSES,
    guideType: HELP_GUIDE_TYPE.OVERVIEW,
    title: `How to read payment statuses and next steps`,
    summary: `Learn what the main payment states mean on the list and detail pages, and how role and status together decide the next action.`,
    category: HELP_GUIDE_CATEGORY.PAYMENTS,
    feature: HELP_GUIDE_FEATURE.PAYMENTS,
    audienceState: HELP_AUDIENCE_STATE.AUTHENTICATED,
    routeAffinity: [`/payments`, `/payments/[paymentRequestId]`],
    order: 38,
    prerequisites: [
      `Open the payments list or a payment detail page so you can compare the guide with the current visible status and role.`,
    ],
    relatedGuides: [
      HELP_GUIDE_SLUG.PAYMENTS_OVERVIEW,
      HELP_GUIDE_SLUG.PAYMENTS_START_PAYMENT,
      HELP_GUIDE_SLUG.PAYMENTS_COMMON_ISSUES,
    ],
  },
  {
    slug: HELP_GUIDE_SLUG.PAYMENTS_COMMON_ISSUES,
    guideType: HELP_GUIDE_TYPE.TROUBLESHOOTING,
    title: `Common payment issues and next steps`,
    summary: `Use this guide when a payment flow is blocked, unclear, or does not move forward as expected.`,
    category: HELP_GUIDE_CATEGORY.PAYMENTS,
    feature: HELP_GUIDE_FEATURE.PAYMENTS,
    audienceState: HELP_AUDIENCE_STATE.AUTHENTICATED,
    routeAffinity: [`/payments`, `/payments/[paymentRequestId]`],
    order: 40,
    prerequisites: [
      `Open the payment you need to review so you can compare the guide with the current state in the app.`,
    ],
    relatedGuides: [
      HELP_GUIDE_SLUG.PAYMENTS_OVERVIEW,
      HELP_GUIDE_SLUG.PAYMENTS_STATUSES,
      HELP_GUIDE_SLUG.PAYMENTS_CREATE_REQUEST,
      HELP_GUIDE_SLUG.PAYMENTS_START_PAYMENT,
    ],
  },
  {
    slug: HELP_GUIDE_SLUG.DOCUMENTS_OVERVIEW,
    guideType: HELP_GUIDE_TYPE.OVERVIEW,
    title: `Documents overview`,
    summary: `Understand how uploads, stored files, and payment attachments fit together across the documents area and related workflows.`,
    category: HELP_GUIDE_CATEGORY.DOCUMENTS,
    feature: HELP_GUIDE_FEATURE.DOCUMENTS,
    audienceState: HELP_AUDIENCE_STATE.AUTHENTICATED,
    routeAffinity: [`/documents`, `/payments/[paymentRequestId]`],
    order: 45,
    prerequisites: [
      `Open the documents area or a payment detail page so you can compare the guide with the current document and attachment surfaces.`,
    ],
    relatedGuides: [
      HELP_GUIDE_SLUG.DOCUMENTS_UPLOAD_AND_ATTACH,
      HELP_GUIDE_SLUG.DOCUMENTS_COMMON_ISSUES,
      HELP_GUIDE_SLUG.PAYMENTS_CREATE_REQUEST,
      HELP_GUIDE_SLUG.PAYMENTS_COMMON_ISSUES,
    ],
  },
  {
    slug: HELP_GUIDE_SLUG.DOCUMENTS_UPLOAD_AND_ATTACH,
    guideType: HELP_GUIDE_TYPE.TASK,
    title: `How to upload and attach documents`,
    summary: `Learn how to add documents in the workspace and prepare them for related flows such as payments.`,
    category: HELP_GUIDE_CATEGORY.DOCUMENTS,
    feature: HELP_GUIDE_FEATURE.DOCUMENTS,
    audienceState: HELP_AUDIENCE_STATE.AUTHENTICATED,
    routeAffinity: [`/documents`, `/payments/[paymentRequestId]`],
    order: 50,
    prerequisites: [`Make sure the file you need is available before you open the documents area or a draft payment.`],
    relatedGuides: [
      HELP_GUIDE_SLUG.DOCUMENTS_OVERVIEW,
      HELP_GUIDE_SLUG.DOCUMENTS_COMMON_ISSUES,
      HELP_GUIDE_SLUG.PAYMENTS_CREATE_REQUEST,
      HELP_GUIDE_SLUG.PAYMENTS_COMMON_ISSUES,
    ],
  },
  {
    slug: HELP_GUIDE_SLUG.DOCUMENTS_COMMON_ISSUES,
    guideType: HELP_GUIDE_TYPE.TROUBLESHOOTING,
    title: `Common document issues and next steps`,
    summary: `Use this guide when a document will not upload, attach, appear, or behave as expected in a payment workflow.`,
    category: HELP_GUIDE_CATEGORY.DOCUMENTS,
    feature: HELP_GUIDE_FEATURE.DOCUMENTS,
    audienceState: HELP_AUDIENCE_STATE.AUTHENTICATED,
    routeAffinity: [`/documents`, `/payments/[paymentRequestId]`],
    order: 55,
    prerequisites: [
      `Open the documents area or affected payment detail page so you can compare the guide with the visible document state.`,
    ],
    relatedGuides: [
      HELP_GUIDE_SLUG.DOCUMENTS_OVERVIEW,
      HELP_GUIDE_SLUG.DOCUMENTS_UPLOAD_AND_ATTACH,
      HELP_GUIDE_SLUG.PAYMENTS_CREATE_REQUEST,
      HELP_GUIDE_SLUG.PAYMENTS_COMMON_ISSUES,
    ],
  },
  {
    slug: HELP_GUIDE_SLUG.SETTINGS_OVERVIEW,
    guideType: HELP_GUIDE_TYPE.OVERVIEW,
    title: `Settings overview`,
    summary: `Understand how profile details, saved preferences, password actions, and verification state come together in the settings area.`,
    category: HELP_GUIDE_CATEGORY.SETTINGS_AND_PROFILE,
    feature: HELP_GUIDE_FEATURE.SETTINGS,
    audienceState: HELP_AUDIENCE_STATE.AUTHENTICATED,
    routeAffinity: [`/settings`],
    order: 58,
    prerequisites: [
      `Open the settings area so you can compare the guide with the profile form, preferences, password controls, and verification card.`,
    ],
    relatedGuides: [
      HELP_GUIDE_SLUG.SETTINGS_PROFILE_AND_SECURITY,
      HELP_GUIDE_SLUG.SETTINGS_COMMON_ISSUES,
      HELP_GUIDE_SLUG.VERIFICATION_HOW_IT_WORKS,
      HELP_GUIDE_SLUG.GETTING_STARTED_OVERVIEW,
    ],
  },
  {
    slug: HELP_GUIDE_SLUG.SETTINGS_PROFILE_AND_SECURITY,
    guideType: HELP_GUIDE_TYPE.TASK,
    title: `How to manage profile, preferences, and password`,
    summary: `Update personal details, save theme and preferred currency, and understand what happens when you create or change your password.`,
    category: HELP_GUIDE_CATEGORY.SETTINGS_AND_PROFILE,
    feature: HELP_GUIDE_FEATURE.SETTINGS,
    audienceState: HELP_AUDIENCE_STATE.AUTHENTICATED,
    routeAffinity: [`/settings`],
    order: 60,
    prerequisites: [`Sign in and open the settings area from the main workspace navigation.`],
    relatedGuides: [
      HELP_GUIDE_SLUG.SETTINGS_OVERVIEW,
      HELP_GUIDE_SLUG.SETTINGS_COMMON_ISSUES,
      HELP_GUIDE_SLUG.VERIFICATION_HOW_IT_WORKS,
      HELP_GUIDE_SLUG.GETTING_STARTED_OVERVIEW,
    ],
  },
  {
    slug: HELP_GUIDE_SLUG.SETTINGS_COMMON_ISSUES,
    guideType: HELP_GUIDE_TYPE.TROUBLESHOOTING,
    title: `Common settings issues and next steps`,
    summary: `Use this guide when profile updates, preference changes, password actions, or account notices in Settings do not behave as expected.`,
    category: HELP_GUIDE_CATEGORY.SETTINGS_AND_PROFILE,
    feature: HELP_GUIDE_FEATURE.SETTINGS,
    audienceState: HELP_AUDIENCE_STATE.AUTHENTICATED,
    routeAffinity: [`/settings`],
    order: 65,
    prerequisites: [
      `Open Settings and compare the guide with the field, notice, or save state that currently looks blocked or unclear.`,
    ],
    relatedGuides: [
      HELP_GUIDE_SLUG.SETTINGS_OVERVIEW,
      HELP_GUIDE_SLUG.SETTINGS_PROFILE_AND_SECURITY,
      HELP_GUIDE_SLUG.VERIFICATION_COMMON_ISSUES,
      HELP_GUIDE_SLUG.GETTING_STARTED_OVERVIEW,
    ],
  },
  {
    slug: HELP_GUIDE_SLUG.VERIFICATION_HOW_IT_WORKS,
    guideType: HELP_GUIDE_TYPE.OVERVIEW,
    title: `How verification works`,
    summary: `Understand the purpose of verification, the states you may see, and what to do when more information is requested.`,
    category: HELP_GUIDE_CATEGORY.VERIFICATION_AND_SECURITY,
    feature: HELP_GUIDE_FEATURE.VERIFICATION,
    audienceState: HELP_AUDIENCE_STATE.AUTHENTICATED,
    routeAffinity: [`/dashboard`, `/settings`],
    order: 70,
    prerequisites: [
      `Open your workspace so you can compare the guide with your current verification status in the app.`,
    ],
    relatedGuides: [
      HELP_GUIDE_SLUG.VERIFICATION_COMPLETE_AND_RECOVER,
      HELP_GUIDE_SLUG.VERIFICATION_COMMON_ISSUES,
      HELP_GUIDE_SLUG.DASHBOARD_OVERVIEW,
      HELP_GUIDE_SLUG.GETTING_STARTED_OVERVIEW,
      HELP_GUIDE_SLUG.SETTINGS_PROFILE_AND_SECURITY,
    ],
  },
  {
    slug: HELP_GUIDE_SLUG.VERIFICATION_COMPLETE_AND_RECOVER,
    guideType: HELP_GUIDE_TYPE.TASK,
    title: `How to complete verification and recover from follow-up requests`,
    summary: `Use the visible verification state to continue, retry, restart, or finish profile prerequisites without taking the wrong recovery step.`,
    category: HELP_GUIDE_CATEGORY.VERIFICATION_AND_SECURITY,
    feature: HELP_GUIDE_FEATURE.VERIFICATION,
    audienceState: HELP_AUDIENCE_STATE.AUTHENTICATED,
    routeAffinity: [`/dashboard`, `/settings`],
    order: 72,
    prerequisites: [
      `Open the dashboard or settings page and identify the exact verification badge or action currently shown in the app.`,
    ],
    relatedGuides: [
      HELP_GUIDE_SLUG.VERIFICATION_HOW_IT_WORKS,
      HELP_GUIDE_SLUG.VERIFICATION_COMMON_ISSUES,
      HELP_GUIDE_SLUG.SETTINGS_PROFILE_AND_SECURITY,
      HELP_GUIDE_SLUG.DASHBOARD_TASKS_AND_NEXT_STEPS,
    ],
  },
  {
    slug: HELP_GUIDE_SLUG.VERIFICATION_COMMON_ISSUES,
    guideType: HELP_GUIDE_TYPE.TROUBLESHOOTING,
    title: `Common verification issues and next steps`,
    summary: `Use this guide when verification is stuck in review, asks for more information, or blocks the action you expected to take next.`,
    category: HELP_GUIDE_CATEGORY.VERIFICATION_AND_SECURITY,
    feature: HELP_GUIDE_FEATURE.VERIFICATION,
    audienceState: HELP_AUDIENCE_STATE.AUTHENTICATED,
    routeAffinity: [`/dashboard`, `/settings`],
    order: 75,
    prerequisites: [
      `Open the dashboard or settings verification area so you can compare the guide with the current badge, message, or action button.`,
    ],
    relatedGuides: [
      HELP_GUIDE_SLUG.VERIFICATION_HOW_IT_WORKS,
      HELP_GUIDE_SLUG.VERIFICATION_COMPLETE_AND_RECOVER,
      HELP_GUIDE_SLUG.SETTINGS_COMMON_ISSUES,
      HELP_GUIDE_SLUG.DASHBOARD_COMMON_ISSUES,
    ],
  },
  {
    slug: HELP_GUIDE_SLUG.CONTACTS_OVERVIEW,
    guideType: HELP_GUIDE_TYPE.OVERVIEW,
    title: `Contacts overview`,
    summary: `Understand how saved contacts support payer, payout, and relationship workflows across the workspace.`,
    category: HELP_GUIDE_CATEGORY.CONTACTS_AND_CONTRACTS,
    feature: HELP_GUIDE_FEATURE.CONTACTS,
    audienceState: HELP_AUDIENCE_STATE.AUTHENTICATED,
    routeAffinity: [`/contacts`, `/contacts/[contactId]/details`, `/payments/start`],
    order: 80,
    prerequisites: [
      `Open the contacts area or a contact-driven payment flow so you can compare the guide with the saved-contact experience in the app.`,
    ],
    relatedGuides: [
      HELP_GUIDE_SLUG.CONTACTS_ADD_AND_USE,
      HELP_GUIDE_SLUG.CONTACTS_COMMON_ISSUES,
      HELP_GUIDE_SLUG.CONTRACTS_OVERVIEW,
      HELP_GUIDE_SLUG.PAYMENTS_START_PAYMENT,
    ],
  },
  {
    slug: HELP_GUIDE_SLUG.CONTACTS_ADD_AND_USE,
    guideType: HELP_GUIDE_TYPE.TASK,
    title: `How to add, search, and use contacts`,
    summary: `Create and update saved contacts, search them quickly, and use the right record in related payment and relationship flows.`,
    category: HELP_GUIDE_CATEGORY.CONTACTS_AND_CONTRACTS,
    feature: HELP_GUIDE_FEATURE.CONTACTS,
    audienceState: HELP_AUDIENCE_STATE.AUTHENTICATED,
    routeAffinity: [`/contacts`, `/contacts/[contactId]/details`, `/payments/start`],
    order: 85,
    prerequisites: [
      `Have the contact email and any name or address details ready before you open the create or edit flow.`,
    ],
    relatedGuides: [
      HELP_GUIDE_SLUG.CONTACTS_OVERVIEW,
      HELP_GUIDE_SLUG.CONTACTS_COMMON_ISSUES,
      HELP_GUIDE_SLUG.CONTRACTS_RELATIONSHIPS_AND_NEXT_STEPS,
      HELP_GUIDE_SLUG.PAYMENTS_START_PAYMENT,
    ],
  },
  {
    slug: HELP_GUIDE_SLUG.CONTACTS_COMMON_ISSUES,
    guideType: HELP_GUIDE_TYPE.TROUBLESHOOTING,
    title: `Common contact issues and next steps`,
    summary: `Use this guide when a contact cannot be found, updated, reused, or linked cleanly into the next workspace step.`,
    category: HELP_GUIDE_CATEGORY.CONTACTS_AND_CONTRACTS,
    feature: HELP_GUIDE_FEATURE.CONTACTS,
    audienceState: HELP_AUDIENCE_STATE.AUTHENTICATED,
    routeAffinity: [`/contacts`, `/contacts/[contactId]/details`],
    order: 90,
    prerequisites: [
      `Open the contacts list or the affected contact detail page so you can compare the current error or missing state with the guide.`,
    ],
    relatedGuides: [
      HELP_GUIDE_SLUG.CONTACTS_OVERVIEW,
      HELP_GUIDE_SLUG.CONTACTS_ADD_AND_USE,
      HELP_GUIDE_SLUG.CONTRACTS_COMMON_ISSUES,
      HELP_GUIDE_SLUG.PAYMENTS_COMMON_ISSUES,
    ],
  },
  {
    slug: HELP_GUIDE_SLUG.CONTRACTS_OVERVIEW,
    guideType: HELP_GUIDE_TYPE.OVERVIEW,
    title: `Contracts overview`,
    summary: `Understand how contract relationships, recent activity, attached files, and payment history are organized in the contracts workspace.`,
    category: HELP_GUIDE_CATEGORY.CONTACTS_AND_CONTRACTS,
    feature: HELP_GUIDE_FEATURE.CONTRACTS,
    audienceState: HELP_AUDIENCE_STATE.AUTHENTICATED,
    routeAffinity: [`/contracts`, `/contracts/[contractId]`],
    order: 100,
    prerequisites: [
      `Open the contracts workspace so you can compare the guide with the current filters, contract rows, and detail navigation.`,
    ],
    relatedGuides: [
      HELP_GUIDE_SLUG.CONTRACTS_RELATIONSHIPS_AND_NEXT_STEPS,
      HELP_GUIDE_SLUG.CONTRACTS_COMMON_ISSUES,
      HELP_GUIDE_SLUG.CONTACTS_OVERVIEW,
      HELP_GUIDE_SLUG.PAYMENTS_OVERVIEW,
    ],
  },
  {
    slug: HELP_GUIDE_SLUG.CONTRACTS_RELATIONSHIPS_AND_NEXT_STEPS,
    guideType: HELP_GUIDE_TYPE.TASK,
    title: `How to review contracts and continue the next step`,
    summary: `Use contract filters, detail pages, and workflow links to move from a contract relationship into the right payment, contact, or document action.`,
    category: HELP_GUIDE_CATEGORY.CONTACTS_AND_CONTRACTS,
    feature: HELP_GUIDE_FEATURE.CONTRACTS,
    audienceState: HELP_AUDIENCE_STATE.AUTHENTICATED,
    routeAffinity: [`/contracts`, `/contracts/[contractId]`, `/contacts`],
    order: 105,
    prerequisites: [
      `Open the contracts workspace and decide whether you are searching, filtering, or continuing into a specific contract detail page.`,
    ],
    relatedGuides: [
      HELP_GUIDE_SLUG.CONTRACTS_OVERVIEW,
      HELP_GUIDE_SLUG.CONTRACTS_COMMON_ISSUES,
      HELP_GUIDE_SLUG.CONTACTS_ADD_AND_USE,
      HELP_GUIDE_SLUG.PAYMENTS_CREATE_REQUEST,
    ],
  },
  {
    slug: HELP_GUIDE_SLUG.CONTRACTS_COMMON_ISSUES,
    guideType: HELP_GUIDE_TYPE.TROUBLESHOOTING,
    title: `Common contract issues and next steps`,
    summary: `Use this guide when contract search results, filters, activity history, or detail follow-up do not match what you expected.`,
    category: HELP_GUIDE_CATEGORY.CONTACTS_AND_CONTRACTS,
    feature: HELP_GUIDE_FEATURE.CONTRACTS,
    audienceState: HELP_AUDIENCE_STATE.AUTHENTICATED,
    routeAffinity: [`/contracts`, `/contracts/[contractId]`],
    order: 110,
    prerequisites: [
      `Open the contracts list or a contract detail page so you can compare the current problem with the visible contract state.`,
    ],
    relatedGuides: [
      HELP_GUIDE_SLUG.CONTRACTS_OVERVIEW,
      HELP_GUIDE_SLUG.CONTRACTS_RELATIONSHIPS_AND_NEXT_STEPS,
      HELP_GUIDE_SLUG.CONTACTS_COMMON_ISSUES,
      HELP_GUIDE_SLUG.PAYMENTS_COMMON_ISSUES,
    ],
  },
  {
    slug: HELP_GUIDE_SLUG.BANKING_OVERVIEW,
    guideType: HELP_GUIDE_TYPE.OVERVIEW,
    title: `Banking overview`,
    summary: `Understand how bank accounts, cards, default methods, and payout destinations are organized in the banking area.`,
    category: HELP_GUIDE_CATEGORY.BANKING_AND_WITHDRAWAL,
    feature: HELP_GUIDE_FEATURE.BANKING,
    audienceState: HELP_AUDIENCE_STATE.AUTHENTICATED,
    routeAffinity: [`/banking`, `/withdraw`, `/payments/start`],
    order: 120,
    prerequisites: [
      `Open the banking page so you can compare the guide with the saved bank-account and card sections currently available.`,
    ],
    relatedGuides: [
      HELP_GUIDE_SLUG.BANKING_ADD_AND_MANAGE_METHODS,
      HELP_GUIDE_SLUG.BANKING_COMMON_ISSUES,
      HELP_GUIDE_SLUG.WITHDRAWAL_OVERVIEW,
      HELP_GUIDE_SLUG.PAYMENTS_START_PAYMENT,
    ],
  },
  {
    slug: HELP_GUIDE_SLUG.BANKING_ADD_AND_MANAGE_METHODS,
    guideType: HELP_GUIDE_TYPE.TASK,
    title: `How to add and manage bank accounts and cards`,
    summary: `Add payout destinations and saved cards, choose the right default method, and keep reusable payment methods ready for later flows.`,
    category: HELP_GUIDE_CATEGORY.BANKING_AND_WITHDRAWAL,
    feature: HELP_GUIDE_FEATURE.BANKING,
    audienceState: HELP_AUDIENCE_STATE.AUTHENTICATED,
    routeAffinity: [`/banking`, `/withdraw`, `/payments/start`],
    order: 125,
    prerequisites: [
      `Have the bank or card details you want to save ready before opening the matching form in Banking.`,
    ],
    relatedGuides: [
      HELP_GUIDE_SLUG.BANKING_OVERVIEW,
      HELP_GUIDE_SLUG.BANKING_COMMON_ISSUES,
      HELP_GUIDE_SLUG.WITHDRAWAL_MOVE_FUNDS,
      HELP_GUIDE_SLUG.PAYMENTS_START_PAYMENT,
    ],
  },
  {
    slug: HELP_GUIDE_SLUG.BANKING_COMMON_ISSUES,
    guideType: HELP_GUIDE_TYPE.TROUBLESHOOTING,
    title: `Common banking issues and next steps`,
    summary: `Use this guide when a bank account or saved card cannot be added, updated, deleted, or selected the way you expect.`,
    category: HELP_GUIDE_CATEGORY.BANKING_AND_WITHDRAWAL,
    feature: HELP_GUIDE_FEATURE.BANKING,
    audienceState: HELP_AUDIENCE_STATE.AUTHENTICATED,
    routeAffinity: [`/banking`, `/withdraw`, `/payments/start`],
    order: 130,
    prerequisites: [
      `Open the banking page so you can compare the guide with the current method list, validation message, or disabled action.`,
    ],
    relatedGuides: [
      HELP_GUIDE_SLUG.BANKING_OVERVIEW,
      HELP_GUIDE_SLUG.BANKING_ADD_AND_MANAGE_METHODS,
      HELP_GUIDE_SLUG.WITHDRAWAL_COMMON_ISSUES,
      HELP_GUIDE_SLUG.PAYMENTS_COMMON_ISSUES,
    ],
  },
  {
    slug: HELP_GUIDE_SLUG.WITHDRAWAL_OVERVIEW,
    guideType: HELP_GUIDE_TYPE.OVERVIEW,
    title: `Withdrawal overview`,
    summary: `Understand how withdrawals and consumer-to-consumer transfers use available balance, saved bank methods, and recent movement history.`,
    category: HELP_GUIDE_CATEGORY.BANKING_AND_WITHDRAWAL,
    feature: HELP_GUIDE_FEATURE.WITHDRAWAL,
    audienceState: HELP_AUDIENCE_STATE.AUTHENTICATED,
    routeAffinity: [`/withdraw`, `/banking`, `/dashboard`],
    order: 140,
    prerequisites: [
      `Open the move-funds page so you can compare the guide with the available-balance view, destination selector, and withdrawal history.`,
    ],
    relatedGuides: [
      HELP_GUIDE_SLUG.WITHDRAWAL_MOVE_FUNDS,
      HELP_GUIDE_SLUG.WITHDRAWAL_COMMON_ISSUES,
      HELP_GUIDE_SLUG.BANKING_OVERVIEW,
      HELP_GUIDE_SLUG.DASHBOARD_OVERVIEW,
    ],
  },
  {
    slug: HELP_GUIDE_SLUG.WITHDRAWAL_MOVE_FUNDS,
    guideType: HELP_GUIDE_TYPE.TASK,
    title: `How to withdraw funds or send a transfer`,
    summary: `Use the move-funds flow to withdraw available balance to a saved bank account or transfer value to another consumer account.`,
    category: HELP_GUIDE_CATEGORY.BANKING_AND_WITHDRAWAL,
    feature: HELP_GUIDE_FEATURE.WITHDRAWAL,
    audienceState: HELP_AUDIENCE_STATE.AUTHENTICATED,
    routeAffinity: [`/withdraw`, `/banking`],
    order: 145,
    prerequisites: [
      `Make sure you have a positive available balance and, for withdrawals, at least one saved bank account.`,
    ],
    relatedGuides: [
      HELP_GUIDE_SLUG.WITHDRAWAL_OVERVIEW,
      HELP_GUIDE_SLUG.WITHDRAWAL_COMMON_ISSUES,
      HELP_GUIDE_SLUG.BANKING_ADD_AND_MANAGE_METHODS,
      HELP_GUIDE_SLUG.DASHBOARD_TASKS_AND_NEXT_STEPS,
    ],
  },
  {
    slug: HELP_GUIDE_SLUG.WITHDRAWAL_COMMON_ISSUES,
    guideType: HELP_GUIDE_TYPE.TROUBLESHOOTING,
    title: `Common withdrawal issues and next steps`,
    summary: `Use this guide when withdrawals or transfers are unavailable, pending, over balance, or blocked by missing payout setup.`,
    category: HELP_GUIDE_CATEGORY.BANKING_AND_WITHDRAWAL,
    feature: HELP_GUIDE_FEATURE.WITHDRAWAL,
    audienceState: HELP_AUDIENCE_STATE.AUTHENTICATED,
    routeAffinity: [`/withdraw`, `/banking`, `/dashboard`],
    order: 150,
    prerequisites: [
      `Open the move-funds page and compare the guide with the current balance, destination, field error, or pending history row.`,
    ],
    relatedGuides: [
      HELP_GUIDE_SLUG.WITHDRAWAL_OVERVIEW,
      HELP_GUIDE_SLUG.WITHDRAWAL_MOVE_FUNDS,
      HELP_GUIDE_SLUG.BANKING_COMMON_ISSUES,
      HELP_GUIDE_SLUG.DASHBOARD_COMMON_ISSUES,
    ],
  },
  {
    slug: HELP_GUIDE_SLUG.EXCHANGE_OVERVIEW,
    guideType: HELP_GUIDE_TYPE.OVERVIEW,
    title: `Exchange overview`,
    summary: `Understand how the main Exchange route combines manual conversion, live rates, automation shortcuts, and dedicated rules and scheduling surfaces.`,
    category: HELP_GUIDE_CATEGORY.EXCHANGE,
    feature: HELP_GUIDE_FEATURE.EXCHANGE,
    audienceState: HELP_AUDIENCE_STATE.AUTHENTICATED,
    routeAffinity: [`/exchange`, `/exchange/rules`, `/exchange/scheduled`],
    order: 160,
    prerequisites: [
      `Open the Exchange area so you can compare the guide with the convert form, live-rate cards, auto-rules section, and scheduled conversions panel.`,
    ],
    relatedGuides: [
      HELP_GUIDE_SLUG.EXCHANGE_CONVERT_AND_AUTOMATE,
      HELP_GUIDE_SLUG.EXCHANGE_COMMON_ISSUES,
      HELP_GUIDE_SLUG.WITHDRAWAL_OVERVIEW,
      HELP_GUIDE_SLUG.BANKING_OVERVIEW,
    ],
  },
  {
    slug: HELP_GUIDE_SLUG.EXCHANGE_CONVERT_AND_AUTOMATE,
    guideType: HELP_GUIDE_TYPE.TASK,
    title: `How to quote, convert, and manage exchange automation`,
    summary: `Use the main Exchange route to get a quote and convert now, then manage auto-rules or scheduled conversions from the dedicated exchange surfaces.`,
    category: HELP_GUIDE_CATEGORY.EXCHANGE,
    feature: HELP_GUIDE_FEATURE.EXCHANGE,
    audienceState: HELP_AUDIENCE_STATE.AUTHENTICATED,
    routeAffinity: [`/exchange`, `/exchange/rules`, `/exchange/scheduled`],
    order: 165,
    prerequisites: [
      `Make sure you have a source balance, two different currencies, and a clear idea whether the action should happen now, through an auto-rule, or on a future schedule.`,
    ],
    relatedGuides: [
      HELP_GUIDE_SLUG.EXCHANGE_OVERVIEW,
      HELP_GUIDE_SLUG.EXCHANGE_COMMON_ISSUES,
      HELP_GUIDE_SLUG.WITHDRAWAL_OVERVIEW,
      HELP_GUIDE_SLUG.BANKING_OVERVIEW,
    ],
  },
  {
    slug: HELP_GUIDE_SLUG.EXCHANGE_COMMON_ISSUES,
    guideType: HELP_GUIDE_TYPE.TROUBLESHOOTING,
    title: `Common exchange issues and next steps`,
    summary: `Use this guide when quotes, balances, rule inputs, or scheduled-conversion states do not behave the way the current exchange surfaces suggest they should.`,
    category: HELP_GUIDE_CATEGORY.EXCHANGE,
    feature: HELP_GUIDE_FEATURE.EXCHANGE,
    audienceState: HELP_AUDIENCE_STATE.AUTHENTICATED,
    routeAffinity: [`/exchange`, `/exchange/rules`, `/exchange/scheduled`],
    order: 170,
    prerequisites: [
      `Open the exact exchange page that is showing the problem so you can compare the guide with the current validation message, disabled action, status badge, or unavailable rates state.`,
    ],
    relatedGuides: [
      HELP_GUIDE_SLUG.EXCHANGE_OVERVIEW,
      HELP_GUIDE_SLUG.EXCHANGE_CONVERT_AND_AUTOMATE,
      HELP_GUIDE_SLUG.WITHDRAWAL_COMMON_ISSUES,
      HELP_GUIDE_SLUG.BANKING_COMMON_ISSUES,
    ],
  },
] as const satisfies readonly HelpGuideDefinition<HelpGuideSlug>[];

export type PublicHelpGuideRegistryEntry = PublicHelpGuideMeta<HelpGuideSlug>;

export const publicHelpGuideRegistry: readonly PublicHelpGuideRegistryEntry[] = [...helpGuideRegistryDefinitions];

export const publicHelpGuideRegistryBySlug: Record<HelpGuideSlug, PublicHelpGuideRegistryEntry> =
  publicHelpGuideRegistry.reduce(
    (accumulator, guide) => {
      accumulator[guide.slug] = guide;
      return accumulator;
    },
    {} as Record<HelpGuideSlug, PublicHelpGuideRegistryEntry>,
  );
