export const HELP_GUIDE_SLUG = {
  GETTING_STARTED_OVERVIEW: `getting-started-overview`,
  DASHBOARD_OVERVIEW: `dashboard-overview`,
  DASHBOARD_TASKS_AND_NEXT_STEPS: `dashboard-tasks-and-next-steps`,
  DASHBOARD_COMMON_ISSUES: `dashboard-common-issues`,
  PAYMENTS_OVERVIEW: `payments-overview`,
  PAYMENTS_CREATE_REQUEST: `payments-create-request`,
  PAYMENTS_START_PAYMENT: `payments-start-payment`,
  PAYMENTS_STATUSES: `payments-statuses-and-next-steps`,
  PAYMENTS_COMMON_ISSUES: `payments-common-issues`,
  DOCUMENTS_OVERVIEW: `documents-overview`,
  DOCUMENTS_UPLOAD_AND_ATTACH: `documents-upload-and-attach`,
  DOCUMENTS_COMMON_ISSUES: `documents-common-issues`,
  CONTACTS_OVERVIEW: `contacts-overview`,
  CONTACTS_ADD_AND_USE: `contacts-add-and-use`,
  CONTACTS_COMMON_ISSUES: `contacts-common-issues`,
  CONTRACTS_OVERVIEW: `contracts-overview`,
  CONTRACTS_RELATIONSHIPS_AND_NEXT_STEPS: `contracts-relationships-and-next-steps`,
  CONTRACTS_COMMON_ISSUES: `contracts-common-issues`,
  BANKING_OVERVIEW: `banking-overview`,
  BANKING_ADD_AND_MANAGE_METHODS: `banking-add-and-manage-methods`,
  BANKING_COMMON_ISSUES: `banking-common-issues`,
  WITHDRAWAL_OVERVIEW: `withdrawal-overview`,
  WITHDRAWAL_MOVE_FUNDS: `withdrawal-move-funds`,
  WITHDRAWAL_COMMON_ISSUES: `withdrawal-common-issues`,
  EXCHANGE_OVERVIEW: `exchange-overview`,
  EXCHANGE_CONVERT_AND_AUTOMATE: `exchange-convert-and-automate`,
  EXCHANGE_COMMON_ISSUES: `exchange-common-issues`,
  SETTINGS_OVERVIEW: `settings-overview`,
  SETTINGS_PROFILE_AND_SECURITY: `settings-profile-and-security`,
  SETTINGS_COMMON_ISSUES: `settings-common-issues`,
  VERIFICATION_HOW_IT_WORKS: `verification-how-it-works`,
  VERIFICATION_COMPLETE_AND_RECOVER: `verification-complete-and-recover`,
  VERIFICATION_COMMON_ISSUES: `verification-common-issues`,
} as const;

export type HelpGuideSlug = (typeof HELP_GUIDE_SLUG)[keyof typeof HELP_GUIDE_SLUG];
