export const CONSUMER_ENDPOINTS = {
  dashboard: { method: `GET`, path: `/consumer/dashboard`, response: `ConsumerDashboardData` },
  paymentsList: {
    method: `GET`,
    path: `/consumer/payments`,
    query: `ConsumerPaymentsListQuery`,
    response: `ConsumerPaymentsResponse`,
  },
  paymentsGet: { method: `GET`, path: `/consumer/payments/:paymentRequestId`, response: `ConsumerPaymentViewResponse` },
  paymentsHistory: {
    method: `GET`,
    path: `/consumer/payments/history`,
    query: `ConsumerPaymentHistoryQuery`,
    response: `ConsumerPaymentHistoryResponse`,
  },
  paymentsBalance: { method: `GET`, path: `/consumer/payments/balance`, response: `ConsumerBalanceResponse` },
  paymentsAvailableBalance: {
    method: `GET`,
    path: `/consumer/payments/balance/available`,
    response: `ConsumerBalanceResponse`,
  },
  paymentsStart: {
    method: `POST`,
    path: `/consumer/payments/start`,
    query: `ConsumerAppScopeQuery`,
    body: `ConsumerStartPaymentPayload`,
    response: `ConsumerStartPaymentResponse`,
  },
  paymentsWithdraw: {
    method: `POST`,
    path: `/consumer/payments/withdraw`,
    body: `ConsumerWithdrawPayload`,
    response: `ConsumerTransferResponse`,
  },
  paymentsTransfer: {
    method: `POST`,
    path: `/consumer/payments/transfer`,
    body: `ConsumerTransferPayload`,
    response: `ConsumerTransferResponse`,
  },
  paymentsGenerateInvoice: {
    method: `POST`,
    path: `/consumer/payments/:paymentRequestId/generate-invoice`,
    response: `ConsumerInvoiceGenerationResponse`,
  },
  paymentRequestsCreate: {
    method: `POST`,
    path: `/consumer/payment-requests`,
    body: `ConsumerCreatePaymentRequestPayload`,
    response: `ConsumerCreatePaymentRequestResponse`,
  },
  paymentRequestsSend: {
    method: `POST`,
    path: `/consumer/payment-requests/:paymentRequestId/send`,
    query: `ConsumerAppScopeQuery`,
  },
  paymentMethodsList: {
    method: `GET`,
    path: `/consumer/payment-methods`,
    response: `ConsumerPaymentMethodsResponse`,
  },
  contactsList: {
    method: `GET`,
    path: `/consumer/contacts`,
    query: `ConsumerContactsListQuery`,
    response: `ConsumerContactsResponse`,
  },
  contactsLookupByEmail: {
    method: `GET`,
    path: `/consumer/contacts/lookup/by-email`,
    response: `ConsumerContactSearchItem`,
  },
  contactsGet: { method: `GET`, path: `/consumer/contacts/:id`, response: `ConsumerContactResponse` },
  contactsDetails: {
    method: `GET`,
    path: `/consumer/contacts/:id/details`,
    response: `ConsumerContactDetailsResponse`,
  },
  contractsList: {
    method: `GET`,
    path: `/consumer/contracts`,
    query: `ConsumerContractsListQuery`,
    response: `ConsumerContractsResponse`,
  },
  contractsDetails: {
    method: `GET`,
    path: `/consumer/contracts/:id/details`,
    response: `ConsumerContractDetailsResponse`,
  },
  documentsList: {
    method: `GET`,
    path: `/consumer/documents`,
    query: `ConsumerDocumentsListQuery`,
    response: `ConsumerDocumentsResponse`,
  },
  documentsAttachToPayment: {
    method: `POST`,
    path: `/consumer/documents/attach-to-payment`,
    body: `ConsumerAttachDocumentsPayload`,
  },
  documentsDetachFromPayment: {
    method: `DELETE`,
    path: `/consumer/documents/payment-attachments/:paymentRequestId/:resourceId`,
  },
  settingsGet: { method: `GET`, path: `/consumer/settings`, response: `ConsumerSettingsResponse` },
  settingsPatch: {
    method: `PATCH`,
    path: `/consumer/settings`,
    body: `ConsumerUpdateSettingsPayload`,
    response: `ConsumerSettingsResponse`,
  },
  profileMe: { method: `GET`, path: `/consumer/profile/me`, response: `ConsumerProfileResponse` },
  profilePatch: {
    method: `PATCH`,
    path: `/consumer/profile`,
    body: `ConsumerUpdateProfilePayload`,
    response: `ConsumerProfileResponse`,
  },
  profilePasswordPatch: { method: `PATCH`, path: `/consumer/profile/password`, body: `ConsumerChangePasswordPayload` },
  exchangeCurrencies: { method: `GET`, path: `/consumer/exchange/currencies`, response: `ConsumerExchangeCurrency[]` },
  exchangeRate: {
    method: `GET`,
    path: `/consumer/exchange/rates`,
    query: `ConsumerExchangeRateQuery`,
    response: `ConsumerExchangeRate`,
  },
  exchangeRatesBatch: {
    method: `POST`,
    path: `/consumer/exchange/rates/batch`,
    body: `ConsumerExchangeRatesBatchQuery`,
    response: `ConsumerExchangeRatesBatchResult`,
  },
  exchangeRules: {
    method: `GET`,
    path: `/consumer/exchange/rules`,
    query: `ConsumerPageQuery`,
    response: `ConsumerExchangeRulesResponse`,
  },
  exchangeScheduled: {
    method: `GET`,
    path: `/consumer/exchange/scheduled`,
    query: `ConsumerPageQuery`,
    response: `ConsumerScheduledConversionsResponse`,
  },
  authLogin: {
    method: `POST`,
    path: `/consumer/auth/login`,
    query: `ConsumerAppScopeQuery`,
    body: `ConsumerLoginBody`,
    response: `ConsumerLoginResponse`,
  },
  authGoogleStart: {
    method: `GET`,
    path: `/consumer/auth/google/start`,
    query: `ConsumerGoogleOAuthStartQuery`,
  },
  authGoogleSignupSession: {
    method: `GET`,
    path: `/consumer/auth/google/signup-session`,
    query: `ConsumerAppScopeQuery`,
    response: `ConsumerGoogleSignupSessionResponse`,
  },
  authGoogleSignupEstablish: {
    method: `POST`,
    path: `/consumer/auth/google/signup-session/establish`,
    query: `ConsumerAppScopeQuery`,
    body: `ConsumerHandoffTokenRequest`,
    response: `ConsumerGoogleSignupSessionResponse`,
  },
  authOAuthComplete: {
    method: `POST`,
    path: `/consumer/auth/oauth/complete`,
    query: `ConsumerAppScopeQuery`,
    body: `ConsumerHandoffTokenRequest`,
    response: `ConsumerOAuthCompleteResponse`,
  },
  authLogout: { method: `POST`, path: `/consumer/auth/logout`, response: `ConsumerAuthLogoutResponse` },
  authRefresh: { method: `POST`, path: `/consumer/auth/refresh`, response: `ConsumerLoginResponse` },
  authLogoutAll: { method: `POST`, path: `/consumer/auth/logout-all`, response: `ConsumerAuthLogoutResponse` },
  authSignup: {
    method: `POST`,
    path: `/consumer/auth/signup`,
    query: `ConsumerAppScopeQuery`,
    body: `ConsumerSignupPayload`,
    response: `ConsumerSignupResponse`,
  },
  authForgotPassword: {
    method: `POST`,
    path: `/consumer/auth/forgot-password`,
    query: `ConsumerAppScopeQuery`,
    body: `ConsumerForgotPasswordBody`,
    response: `ConsumerForgotPasswordResponse`,
  },
  authResetPassword: {
    method: `POST`,
    path: `/consumer/auth/password/reset`,
    body: `ConsumerResetPasswordBody`,
    response: `ConsumerMutationResult`,
  },
  stripeCheckoutSession: {
    method: `POST`,
    path: `/consumer/stripe/:paymentRequestId/stripe-session`,
    query: `ConsumerStripeCheckoutQuery`,
    response: `ConsumerStripeCheckoutSessionResponse`,
  },
  stripeSetupIntentCreate: {
    method: `POST`,
    path: `/consumer/stripe/intents`,
    response: `ConsumerStripeSetupIntentResponse`,
  },
  stripeConfirm: {
    method: `POST`,
    path: `/consumer/stripe/confirm`,
    body: `ConsumerConfirmStripeSetupIntentPayload`,
  },
  stripePayWithSavedMethod: {
    method: `POST`,
    path: `/consumer/stripe/:paymentRequestId/pay-with-saved-method`,
    query: `ConsumerAppScopeQuery`,
    body: `ConsumerPayWithSavedPaymentMethodPayload`,
    response: `ConsumerPayWithSavedMethodResponse`,
  },
  verificationSessionCreate: {
    method: `POST`,
    path: `/consumer/verification/sessions`,
    response: `ConsumerVerificationSessionResponse`,
  },
} as const;

export type ConsumerEndpointKey = keyof typeof CONSUMER_ENDPOINTS;
export type ConsumerEndpointDefinition = (typeof CONSUMER_ENDPOINTS)[ConsumerEndpointKey];
