export default function DocumentsLoading() {
  return (
    <div
      className={`
        space-y-6
        animate-pulse
      `}
    >
      <div
        className={`
          flex
          items-center
          justify-between
        `}
      >
        <div
          className={`
            h-8
            w-32
            rounded
            bg-slate-200
            dark:bg-slate-700
          `}
        />
        <div
          className={`
            h-11
            w-32
            rounded-lg
            bg-slate-200
            dark:bg-slate-700
          `}
        />
      </div>

      <div
        className={`
          grid
          gap-4
          sm:grid-cols-2
          lg:grid-cols-3
        `}
      >
        {[1, 2, 3, 4, 5, 6].map((i) => (
          <div
            key={i}
            className={`
              h-48
              rounded-xl
              bg-slate-200
              dark:bg-slate-700
            `}
          />
        ))}
      </div>
    </div>
  );
}
