/* eslint-disable max-len */
import {
  type TransactionActionType,
  type CurrencyCode,
  type TransactionStatus,
  type TransactionType,
  type TransactionFeesType,
} from '@remoola/database';

import type { IBaseModel } from './base.model';

/* record should be created at the beginning of the payment request */
export type ITransactionModel = {
  consumerId: string;
  code?: string; // autogenerated on pg // ??? (Tx ID - 6 symbols text auto generated on db layer by default)
  type: TransactionType;
  originAmount: number; // in cents
  currencyCode: CurrencyCode;
  actionType: TransactionActionType;
  status: TransactionStatus; // (status changes depending on the status of stripe or by the admin depending on the physical receipt of money)

  createdBy: string; // ???
  updatedBy: string; // ???
  deletedBy?: string; // ???

  paymentRequestId?: string | null | undefined;
  feesType?: TransactionFeesType | null | undefined;
  feesAmount?: number | null | undefined;
  stripeId?: string | null | undefined;
  stripeFeeInPercents?: number | null | undefined;
} & IBaseModel;
