import { ConsumerRoles, type TConsumerRole } from '@remoola/api-types';

export const CONSUMER_ROLE = ConsumerRoles;
export type IConsumerRole = TConsumerRole;

export const CONSUMER_ROLE_LABEL = {
  [CONSUMER_ROLE.FOUNDER]: `Founder`,
  [CONSUMER_ROLE.FINANCE]: `Finance`,
  [CONSUMER_ROLE.MARKETING]: `Marketing`,
  [CONSUMER_ROLE.CUSTOMER_SUPPORT]: `Customer support`,
  [CONSUMER_ROLE.SALES]: `Sales`,
  [CONSUMER_ROLE.LEGAL]: `Legal`,
  [CONSUMER_ROLE.HUMAN_RESOURCE]: `Human resource`,
  [CONSUMER_ROLE.OPERATIONS]: `Operations`,
  [CONSUMER_ROLE.COMPLIANCE]: `Compliance`,
  [CONSUMER_ROLE.PRODUCT]: `Product`,
  [CONSUMER_ROLE.ENGINEERING]: `Engineering`,
  [CONSUMER_ROLE.ANALYSIS_DATA]: `Analysis/Data`,
  [CONSUMER_ROLE.OTHER]: `Other`,
} as const;
export type IConsumerRoleLabel = (typeof CONSUMER_ROLE_LABEL)[keyof typeof CONSUMER_ROLE_LABEL];

export const ROLE_LABEL = {
  [CONSUMER_ROLE.FOUNDER]: CONSUMER_ROLE_LABEL[CONSUMER_ROLE.FOUNDER],
  [CONSUMER_ROLE.FINANCE]: CONSUMER_ROLE_LABEL[CONSUMER_ROLE.FINANCE],
  [CONSUMER_ROLE.MARKETING]: CONSUMER_ROLE_LABEL[CONSUMER_ROLE.MARKETING],
  [CONSUMER_ROLE.CUSTOMER_SUPPORT]: CONSUMER_ROLE_LABEL[CONSUMER_ROLE.CUSTOMER_SUPPORT],
  [CONSUMER_ROLE.SALES]: CONSUMER_ROLE_LABEL[CONSUMER_ROLE.SALES],
  [CONSUMER_ROLE.LEGAL]: CONSUMER_ROLE_LABEL[CONSUMER_ROLE.LEGAL],
  [CONSUMER_ROLE.HUMAN_RESOURCE]: CONSUMER_ROLE_LABEL[CONSUMER_ROLE.HUMAN_RESOURCE],
  [CONSUMER_ROLE.OPERATIONS]: CONSUMER_ROLE_LABEL[CONSUMER_ROLE.OPERATIONS],
  [CONSUMER_ROLE.COMPLIANCE]: CONSUMER_ROLE_LABEL[CONSUMER_ROLE.COMPLIANCE],
  [CONSUMER_ROLE.PRODUCT]: CONSUMER_ROLE_LABEL[CONSUMER_ROLE.PRODUCT],
  [CONSUMER_ROLE.ENGINEERING]: CONSUMER_ROLE_LABEL[CONSUMER_ROLE.ENGINEERING],
  [CONSUMER_ROLE.ANALYSIS_DATA]: CONSUMER_ROLE_LABEL[CONSUMER_ROLE.ANALYSIS_DATA],
  [CONSUMER_ROLE.OTHER]: CONSUMER_ROLE_LABEL[CONSUMER_ROLE.OTHER],
};

export const LABEL_ROLE = {
  [CONSUMER_ROLE_LABEL[CONSUMER_ROLE.FOUNDER]]: CONSUMER_ROLE.FOUNDER,
  [CONSUMER_ROLE_LABEL[CONSUMER_ROLE.FINANCE]]: CONSUMER_ROLE.FINANCE,
  [CONSUMER_ROLE_LABEL[CONSUMER_ROLE.MARKETING]]: CONSUMER_ROLE.MARKETING,
  [CONSUMER_ROLE_LABEL[CONSUMER_ROLE.CUSTOMER_SUPPORT]]: CONSUMER_ROLE.CUSTOMER_SUPPORT,
  [CONSUMER_ROLE_LABEL[CONSUMER_ROLE.SALES]]: CONSUMER_ROLE.SALES,
  [CONSUMER_ROLE_LABEL[CONSUMER_ROLE.LEGAL]]: CONSUMER_ROLE.LEGAL,
  [CONSUMER_ROLE_LABEL[CONSUMER_ROLE.HUMAN_RESOURCE]]: CONSUMER_ROLE.HUMAN_RESOURCE,
  [CONSUMER_ROLE_LABEL[CONSUMER_ROLE.OPERATIONS]]: CONSUMER_ROLE.OPERATIONS,
  [CONSUMER_ROLE_LABEL[CONSUMER_ROLE.COMPLIANCE]]: CONSUMER_ROLE.COMPLIANCE,
  [CONSUMER_ROLE_LABEL[CONSUMER_ROLE.PRODUCT]]: CONSUMER_ROLE.PRODUCT,
  [CONSUMER_ROLE_LABEL[CONSUMER_ROLE.ENGINEERING]]: CONSUMER_ROLE.ENGINEERING,
  [CONSUMER_ROLE_LABEL[CONSUMER_ROLE.ANALYSIS_DATA]]: CONSUMER_ROLE.ANALYSIS_DATA,
  [CONSUMER_ROLE_LABEL[CONSUMER_ROLE.OTHER]]: CONSUMER_ROLE.OTHER,
};
