export const HOW_DID_HEAR_ABOUT_US = {
  EMPLOYER_COMPANY: `EMPLOYER_COMPANY`,
  EMPLOYEE_CONTRACTOR: `EMPLOYEE_CONTRACTOR`,
  REFERRED_RECOMMENDED: `REFERRED_RECOMMENDED`,
  EMAIL_INVITE: `EMAIL_INVITE`,
  GOOGLE: `GOOGLE`,
  FACEBOOK: `FACEBOOK`,
  TWITTER: `TWITTER`,
  LINKED_IN: `LINKED_IN`,
  OTHER: `OTHER`,
} as const;
export type IHowDidHearAboutUs = (typeof HOW_DID_HEAR_ABOUT_US)[keyof typeof HOW_DID_HEAR_ABOUT_US];

export const HOW_DID_HEAR_ABOUT_US_LABEL = {
  [HOW_DID_HEAR_ABOUT_US.EMPLOYER_COMPANY]: `Employer / Company`,
  [HOW_DID_HEAR_ABOUT_US.EMPLOYEE_CONTRACTOR]: `Employee / Contractor`,
  [HOW_DID_HEAR_ABOUT_US.REFERRED_RECOMMENDED]: `Referred / Recommended`,
  [HOW_DID_HEAR_ABOUT_US.EMAIL_INVITE]: `Email invite`,
  [HOW_DID_HEAR_ABOUT_US.GOOGLE]: `Google`,
  [HOW_DID_HEAR_ABOUT_US.FACEBOOK]: `Facebook`,
  [HOW_DID_HEAR_ABOUT_US.TWITTER]: `Twitter`,
  [HOW_DID_HEAR_ABOUT_US.LINKED_IN]: `LinkedIn`,
  [HOW_DID_HEAR_ABOUT_US.OTHER]: `Other`,
} as const;
export type IHowDidHearAboutUsLabel = (typeof HOW_DID_HEAR_ABOUT_US_LABEL)[keyof typeof HOW_DID_HEAR_ABOUT_US_LABEL];

export const HOW_LABEL = {
  [HOW_DID_HEAR_ABOUT_US.EMPLOYER_COMPANY]: HOW_DID_HEAR_ABOUT_US_LABEL[HOW_DID_HEAR_ABOUT_US.EMPLOYER_COMPANY],
  [HOW_DID_HEAR_ABOUT_US.EMPLOYEE_CONTRACTOR]: HOW_DID_HEAR_ABOUT_US_LABEL[HOW_DID_HEAR_ABOUT_US.EMPLOYEE_CONTRACTOR],
  [HOW_DID_HEAR_ABOUT_US.REFERRED_RECOMMENDED]: HOW_DID_HEAR_ABOUT_US_LABEL[HOW_DID_HEAR_ABOUT_US.REFERRED_RECOMMENDED],
  [HOW_DID_HEAR_ABOUT_US.EMAIL_INVITE]: HOW_DID_HEAR_ABOUT_US_LABEL[HOW_DID_HEAR_ABOUT_US.EMAIL_INVITE],
  [HOW_DID_HEAR_ABOUT_US.GOOGLE]: HOW_DID_HEAR_ABOUT_US_LABEL[HOW_DID_HEAR_ABOUT_US.GOOGLE],
  [HOW_DID_HEAR_ABOUT_US.FACEBOOK]: HOW_DID_HEAR_ABOUT_US_LABEL[HOW_DID_HEAR_ABOUT_US.FACEBOOK],
  [HOW_DID_HEAR_ABOUT_US.TWITTER]: HOW_DID_HEAR_ABOUT_US_LABEL[HOW_DID_HEAR_ABOUT_US.TWITTER],
  [HOW_DID_HEAR_ABOUT_US.LINKED_IN]: HOW_DID_HEAR_ABOUT_US_LABEL[HOW_DID_HEAR_ABOUT_US.LINKED_IN],
  [HOW_DID_HEAR_ABOUT_US.OTHER]: HOW_DID_HEAR_ABOUT_US_LABEL[HOW_DID_HEAR_ABOUT_US.OTHER],
};

export const LABEL_HOW = {
  [HOW_DID_HEAR_ABOUT_US_LABEL[HOW_DID_HEAR_ABOUT_US.EMPLOYER_COMPANY]]: HOW_DID_HEAR_ABOUT_US.EMPLOYER_COMPANY,
  [HOW_DID_HEAR_ABOUT_US_LABEL[HOW_DID_HEAR_ABOUT_US.EMPLOYEE_CONTRACTOR]]: HOW_DID_HEAR_ABOUT_US.EMPLOYEE_CONTRACTOR,
  [HOW_DID_HEAR_ABOUT_US_LABEL[HOW_DID_HEAR_ABOUT_US.REFERRED_RECOMMENDED]]: HOW_DID_HEAR_ABOUT_US.REFERRED_RECOMMENDED,
  [HOW_DID_HEAR_ABOUT_US_LABEL[HOW_DID_HEAR_ABOUT_US.EMAIL_INVITE]]: HOW_DID_HEAR_ABOUT_US.EMAIL_INVITE,
  [HOW_DID_HEAR_ABOUT_US_LABEL[HOW_DID_HEAR_ABOUT_US.GOOGLE]]: HOW_DID_HEAR_ABOUT_US.GOOGLE,
  [HOW_DID_HEAR_ABOUT_US_LABEL[HOW_DID_HEAR_ABOUT_US.FACEBOOK]]: HOW_DID_HEAR_ABOUT_US.FACEBOOK,
  [HOW_DID_HEAR_ABOUT_US_LABEL[HOW_DID_HEAR_ABOUT_US.TWITTER]]: HOW_DID_HEAR_ABOUT_US.TWITTER,
  [HOW_DID_HEAR_ABOUT_US_LABEL[HOW_DID_HEAR_ABOUT_US.LINKED_IN]]: HOW_DID_HEAR_ABOUT_US.LINKED_IN,
  [HOW_DID_HEAR_ABOUT_US_LABEL[HOW_DID_HEAR_ABOUT_US.OTHER]]: HOW_DID_HEAR_ABOUT_US.OTHER,
};
