export const ORGANIZATION_SIZE = {
  SMALL: `SMALL`,
  MEDIUM: `MEDIUM`,
  LARGE: `LARGE`,
} as const;

export type IOrganizationSize = (typeof ORGANIZATION_SIZE)[keyof typeof ORGANIZATION_SIZE];

export const ORGANIZATION_SIZE_LABEL = {
  [ORGANIZATION_SIZE.SMALL]: `1-10 team members`,
  [ORGANIZATION_SIZE.MEDIUM]: `11-100 team members`,
  [ORGANIZATION_SIZE.LARGE]: `100+ team members`,
} as const;

export type IOrganizationSizeLabel = (typeof ORGANIZATION_SIZE_LABEL)[keyof typeof ORGANIZATION_SIZE_LABEL];

export const SIZE_LABEL = {
  [ORGANIZATION_SIZE.SMALL]: ORGANIZATION_SIZE_LABEL[ORGANIZATION_SIZE.SMALL],
  [ORGANIZATION_SIZE.MEDIUM]: ORGANIZATION_SIZE_LABEL[ORGANIZATION_SIZE.MEDIUM],
  [ORGANIZATION_SIZE.LARGE]: ORGANIZATION_SIZE_LABEL[ORGANIZATION_SIZE.LARGE],
};

export const LABEL_SIZE = {
  [ORGANIZATION_SIZE_LABEL[ORGANIZATION_SIZE.SMALL]]: ORGANIZATION_SIZE.SMALL,
  [ORGANIZATION_SIZE_LABEL[ORGANIZATION_SIZE.MEDIUM]]: ORGANIZATION_SIZE.MEDIUM,
  [ORGANIZATION_SIZE_LABEL[ORGANIZATION_SIZE.LARGE]]: ORGANIZATION_SIZE.LARGE,
};
