export const StripeEvent = {
  SetupIntentCreated: `setup_intent.created`,
  SetupIntentSucceeded: `setup_intent.succeeded`,
  PaymentIntentCreated: `payment_intent.created`,
  InvoiceCreated: `invoice.created`,
  InvoiceItemUpdated: `invoiceitem.updated`,
  InvoiceItemCreated: `invoiceitem.created`,
  CustomerUpdated: `customer.updated`,
  CustomerCreated: `customer.created`,
  CustomerSubscriptionUpdated: `customer.subscription.updated`,
  PaymentIntentCanceled: `payment_intent.canceled`,
  InvoiceVoided: `invoice.voided`,
  InvoiceUpdated: `invoice.updated`,
  InvoiceFinalized: `invoice.finalized`,
  InvoicePaymentSucceeded: `invoice.payment_succeeded`,
  InvoicePaid: `invoice.paid`,
  PaymentIntentSucceeded: `payment_intent.succeeded`,
  ChargeSucceeded: `charge.succeeded`,
  PaymentMethodAttached: `payment_method.attached`,
  SubscriptionScheduleUpdated: `subscription_schedule.updated`,
  SubscriptionScheduleCreated: `subscription_schedule.created`,
  CustomerSubscriptionCreated: `customer.subscription.created`,
  PriceCreated: `price.created`,
  PlanCreated: `plan.created`,
  ProductCreated: `product.created`,
  CustomerSourceCreated: `customer.source.created`,
  SubscriptionScheduleReleased: `subscription_schedule.released`,
  SubscriptionScheduleCanceled: `subscription_schedule.canceled`,
  CustomerSubscriptionDeleted: `customer.subscription.deleted`,
  InvoicePaymentFailed: `invoice.payment_failed`,
  PaymentIntentPaymentFailed: `payment_intent.payment_failed`,
  ChargeFailed: `charge.failed`,
  SetupIntentSetupFailed: `setup_intent.setup_failed`,
  SetupIntentCanceled: `setup_intent.canceled`,
  QuoteFinalized: `quote.finalized`,
  QuoteCreated: `quote.created`,
  QuoteCanceled: `quote.canceled`,
  QuoteAccepted: `quote.accepted`,
  ProductUpdated: `product.updated`,
  ProductDeleted: `product.deleted`,
  PriceUpdated: `price.updated`,
  PlanUpdated: `plan.updated`,
  PriceDeleted: `price.deleted`,
  PlanDeleted: `plan.deleted`,
  BalanceAvailable: `balance.available`,
  PaymentLinkUpdated: `payment_link.updated`,
  PaymentLinkCreated: `payment_link.created`,
  PaymentIntentAmountCapturableUpdated: `payment_intent.amount_capturable_updated`,
  InvoicePaymentActionRequired: `invoice.payment_action_required`,
  PaymentIntentRequiresAction: `payment_intent.requires_action`,
  IdentityVerificationSessionRedacted: `identity.verification_session.redacted`,
  IdentityVerificationSessionCreated: `identity.verification_session.created`,
  IdentityVerificationSessionCanceled: `identity.verification_session.canceled`,
  CustomerSourceUpdated: `customer.source.updated`,
  CustomerDeleted: `customer.deleted`,
  CheckoutSessionCompleted: `checkout.session.completed`,
  CheckoutSessionAsyncPaymentFailed: `checkout.session.async_payment_failed`,
  PaymentIntentProcessing: `payment_intent.processing`,
  ChargePending: `charge.pending`,
  ChargeRefunded: `charge.refunded`,
  ChargeRefundUpdated: `charge.refund.updated`,
  ChargeDisputeCreated: `charge.dispute.created`,
  ChargeCaptured: `charge.captured`,
} as const

export type StripeEventValue = (typeof StripeEvent)[keyof typeof StripeEvent]

export const PaymentMethod = { Card: `card` } as const
export type PaymentMethodValue = (typeof PaymentMethod)[keyof typeof PaymentMethod]
