export const stripeEvent = {
  setupIntentCreated: `setup_intent.created`,
  setupIntentSucceeded: `setup_intent.succeeded`,
  paymentIntentCreated: `payment_intent.created`,
  invoiceCreated: `invoice.created`,
  invoiceItemUpdated: `invoiceitem.updated`,
  invoiceItemCreated: `invoiceitem.created`,
  customerUpdated: `customer.updated`,
  customerCreated: `customer.created`,
  customerSubscriptionUpdated: `customer.subscription.updated`,
  paymentIntentCanceled: `payment_intent.canceled`,
  invoiceVoided: `invoice.voided`,
  invoiceUpdated: `invoice.updated`,
  invoiceFinalized: `invoice.finalized`,
  invoicePaymentSucceeded: `invoice.payment_succeeded`,
  invoicePaid: `invoice.paid`,
  paymentIntentSucceeded: `payment_intent.succeeded`,
  chargeSucceeded: `charge.succeeded`,
  paymentMethodAttached: `payment_method.attached`,
  subscriptionScheduleUpdated: `subscription_schedule.updated`,
  subscriptionScheduleCreated: `subscription_schedule.created`,
  customerSubscriptionCreated: `customer.subscription.created`,
  priceCreated: `price.created`,
  planCreated: `plan.created`,
  productCreated: `product.created`,
  customerSourceCreated: `customer.source.created`,
  subscriptionScheduleReleased: `subscription_schedule.released`,
  subscriptionScheduleCanceled: `subscription_schedule.canceled`,
  customerSubscriptionDeleted: `customer.subscription.deleted`,
  invoicePaymentFailed: `invoice.payment_failed`,
  paymentIntentPaymentFailed: `payment_intent.payment_failed`,
  chargeFailed: `charge.failed`,
  setupIntentSetupFailed: `setup_intent.setup_failed`,
  setupIntentCanceled: `setup_intent.canceled`,
  quoteFinalized: `quote.finalized`,
  quoteCreated: `quote.created`,
  quoteCanceled: `quote.canceled`,
  quoteAccepted: `quote.accepted`,
  productUpdated: `product.updated`,
  productDeleted: `product.deleted`,
  priceUpdated: `price.updated`,
  planUpdated: `plan.updated`,
  priceDeleted: `price.deleted`,
  planDeleted: `plan.deleted`,
  balanceAvailable: `balance.available`,
  paymentLinkUpdated: `payment_link.updated`,
  paymentLinkCreated: `payment_link.created`,
  paymentIntentAmountCapturableUpdated: `payment_intent.amount_capturable_updated`,
  invoicePaymentActionRequired: `invoice.payment_action_required`,
  paymentIntentRequiresAction: `payment_intent.requires_action`,
  identityVerificationSessionRedacted: `identity.verification_session.redacted`,
  identityVerificationSessionCreated: `identity.verification_session.created`,
  identityVerificationSessionCanceled: `identity.verification_session.canceled`,
  customerSourceUpdated: `customer.source.updated`,
  customerDeleted: `customer.deleted`,
  checkoutSessionCompleted: `checkout.session.completed`,
  checkoutSessionAsyncPaymentFailed: `checkout.session.async_payment_failed`,
  paymentIntentProcessing: `payment_intent.processing`,
  chargePending: `charge.pending`,
  chargeRefunded: `charge.refunded`,
  chargeRefundUpdated: `charge.refund.updated`,
  chargeDisputeCreated: `charge.dispute.created`,
  chargeCaptured: `charge.captured`,
} as const

export type StripeEvent = ValueOf<typeof stripeEvent>

export const paymentMethod = { card: `card` } as const
export type PaymentMethod = ValueOf<typeof paymentMethod>
