export const ACCOUNT_TYPE = {
  BUSINESS: `BUSINESS`,
  CONTRACTOR: `CONTRACTOR`,
} as const;
export type TAccountType = (typeof ACCOUNT_TYPE)[keyof typeof ACCOUNT_TYPE];

export const CONTRACTOR_KIND = {
  ENTITY: `ENTITY`,
  INDIVIDUAL: `INDIVIDUAL`,
} as const;
export type TContractorKind = (typeof CONTRACTOR_KIND)[keyof typeof CONTRACTOR_KIND];

export const LEGAL_STATUS = {
  INDIVIDUAL: `INDIVIDUAL`,
  INDIVIDUAL_ENTREPRENEUR: `INDIVIDUAL_ENTREPRENEUR`,
  SOLE_TRADER: `SOLE_TRADER`,
} as const;
export type TLegalStatus = (typeof LEGAL_STATUS)[keyof typeof LEGAL_STATUS];

export const ORGANIZATION_SIZE = {
  SMALL: `SMALL`,
  MEDIUM: `MEDIUM`,
  LARGE: `LARGE`,
} as const;
export type TOrganizationSize = (typeof ORGANIZATION_SIZE)[keyof typeof ORGANIZATION_SIZE];

export const CONSUMER_ROLE = {
  FOUNDER: `FOUNDER`,
  FINANCE: `FINANCE`,
  MARKETING: `MARKETING`,
  CUSTOMER_SUPPORT: `CUSTOMER_SUPPORT`,
  SALES: `SALES`,
  LEGAL: `LEGAL`,
  HUMAN_RESOURCE: `HUMAN_RESOURCE`,
  OPERATIONS: `OPERATIONS`,
  COMPLIANCE: `COMPLIANCE`,
  PRODUCT: `PRODUCT`,
  ENGINEERING: `ENGINEERING`,
  ANALYSIS_DATA: `ANALYSIS_DATA`,
  OTHER: `OTHER`,
} as const;
export type TConsumerRole = (typeof CONSUMER_ROLE)[keyof typeof CONSUMER_ROLE];

export const HOW_DID_HEAR_ABOUT_US = {
  EMPLOYER_COMPANY: `EMPLOYER_COMPANY`,
  EMPLOYEE_CONTRACTOR: `EMPLOYEE_CONTRACTOR`,
  REFERRED_RECOMMENDED: `REFERRED_RECOMMENDED`,
  EMAIL_INVITE: `EMAIL_INVITE`,
  GOOGLE: `GOOGLE`,
  FACEBOOK: `FACEBOOK`,
  TWITTER: `TWITTER`,
  LINKED_IN: `LINKED_IN`,
  OTHER: `OTHER`,
} as const;
export type THowDidHearAboutUs = (typeof HOW_DID_HEAR_ABOUT_US)[keyof typeof HOW_DID_HEAR_ABOUT_US];
export const HOW_DID_HEAR_ABOUT_US_VALUES = [
  HOW_DID_HEAR_ABOUT_US.EMPLOYER_COMPANY,
  HOW_DID_HEAR_ABOUT_US.EMPLOYEE_CONTRACTOR,
  HOW_DID_HEAR_ABOUT_US.REFERRED_RECOMMENDED,
  HOW_DID_HEAR_ABOUT_US.EMAIL_INVITE,
  HOW_DID_HEAR_ABOUT_US.GOOGLE,
  HOW_DID_HEAR_ABOUT_US.FACEBOOK,
  HOW_DID_HEAR_ABOUT_US.TWITTER,
  HOW_DID_HEAR_ABOUT_US.LINKED_IN,
  HOW_DID_HEAR_ABOUT_US.OTHER,
] as const;

export const AUTH_RATE_LIMIT_MESSAGE = `Too many attempts. Please wait a few minutes and try again.`;

const VERIFICATION_STATUS = {
  PENDING: `PENDING`,
  APPROVED: `APPROVED`,
  MORE_INFO: `MORE_INFO`,
  REJECTED: `REJECTED`,
  FLAGGED: `FLAGGED`,
} as const;
export type TVerificationStatus = (typeof VERIFICATION_STATUS)[keyof typeof VERIFICATION_STATUS];
