#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

yarn lint
yarn workspace @remoola/consumer run test --verbose --coverage=false
yarn workspace @remoola/api run test --passWithNoTests --verbose --coverage=false
