import { HELP_GUIDE_SLUG, type HelpGuideSlug } from '../guide-slugs';
import {
  HELP_AUDIENCE_STATE,
  HELP_GUIDE_CATEGORY,
  HELP_GUIDE_FEATURE,
  HELP_GUIDE_TYPE,
  type HelpGuideDefinition,
} from '../guide-types';

export const paymentsHelpGuideDefinitions = [
  {
    slug: HELP_GUIDE_SLUG.PAYMENTS_OVERVIEW,
    guideType: HELP_GUIDE_TYPE.OVERVIEW,
    title: `Payments overview`,
    summary: `Understand the payments area, the main actions you can take there, and which routes support each step.`,
    category: HELP_GUIDE_CATEGORY.PAYMENTS,
    feature: HELP_GUIDE_FEATURE.PAYMENTS,
    audienceState: HELP_AUDIENCE_STATE.AUTHENTICATED,
    routeAffinity: [`/payments`, `/payments/new-request`, `/payments/start`, `/payments/[paymentRequestId]`],
    order: 20,
    prerequisites: [`Open the payments area from the authenticated workspace navigation.`],
    relatedGuides: [
      HELP_GUIDE_SLUG.PAYMENTS_CREATE_REQUEST,
      HELP_GUIDE_SLUG.PAYMENTS_START_PAYMENT,
      HELP_GUIDE_SLUG.PAYMENTS_STATUSES,
      HELP_GUIDE_SLUG.PAYMENTS_COMMON_ISSUES,
    ],
  },
  {
    slug: HELP_GUIDE_SLUG.PAYMENTS_CREATE_REQUEST,
    guideType: HELP_GUIDE_TYPE.TASK,
    title: `How to create a payment request`,
    summary: `Create a payment request when you need another party to review and pay through the platform.`,
    category: HELP_GUIDE_CATEGORY.PAYMENTS,
    feature: HELP_GUIDE_FEATURE.PAYMENTS,
    audienceState: HELP_AUDIENCE_STATE.AUTHENTICATED,
    routeAffinity: [`/payments`, `/payments/new-request`],
    order: 30,
    prerequisites: [
      `Be signed in to the workspace.`,
      `Have the recipient email, amount, currency, and any due date or description ready before you start.`,
    ],
    relatedGuides: [
      HELP_GUIDE_SLUG.PAYMENTS_OVERVIEW,
      HELP_GUIDE_SLUG.DOCUMENTS_UPLOAD_AND_ATTACH,
      HELP_GUIDE_SLUG.PAYMENTS_COMMON_ISSUES,
    ],
  },
  {
    slug: HELP_GUIDE_SLUG.PAYMENTS_START_PAYMENT,
    guideType: HELP_GUIDE_TYPE.TASK,
    title: `How to start a payment`,
    summary: `Start a payer-side one-off payment, choose the settlement method, and handle unknown recipients without leaving the workspace.`,
    category: HELP_GUIDE_CATEGORY.PAYMENTS,
    feature: HELP_GUIDE_FEATURE.PAYMENTS,
    audienceState: HELP_AUDIENCE_STATE.AUTHENTICATED,
    routeAffinity: [`/payments`, `/payments/start`, `/payments/[paymentRequestId]`],
    order: 35,
    prerequisites: [
      `Be signed in to the workspace.`,
      `Have the recipient email, amount, and settlement method ready before you submit the flow.`,
    ],
    relatedGuides: [
      HELP_GUIDE_SLUG.PAYMENTS_OVERVIEW,
      HELP_GUIDE_SLUG.PAYMENTS_CREATE_REQUEST,
      HELP_GUIDE_SLUG.PAYMENTS_STATUSES,
      HELP_GUIDE_SLUG.PAYMENTS_COMMON_ISSUES,
    ],
  },
  {
    slug: HELP_GUIDE_SLUG.PAYMENTS_STATUSES,
    guideType: HELP_GUIDE_TYPE.OVERVIEW,
    title: `How to read payment statuses and next steps`,
    summary: `Learn what the main payment states mean on the list and detail pages, and how role and status together decide the next action.`,
    category: HELP_GUIDE_CATEGORY.PAYMENTS,
    feature: HELP_GUIDE_FEATURE.PAYMENTS,
    audienceState: HELP_AUDIENCE_STATE.AUTHENTICATED,
    routeAffinity: [`/payments`, `/payments/[paymentRequestId]`],
    order: 38,
    prerequisites: [
      `Open the payments list or a payment detail page so you can compare the guide with the current visible status and role.`,
    ],
    relatedGuides: [
      HELP_GUIDE_SLUG.PAYMENTS_OVERVIEW,
      HELP_GUIDE_SLUG.PAYMENTS_START_PAYMENT,
      HELP_GUIDE_SLUG.PAYMENTS_COMMON_ISSUES,
    ],
  },
  {
    slug: HELP_GUIDE_SLUG.PAYMENTS_COMMON_ISSUES,
    guideType: HELP_GUIDE_TYPE.TROUBLESHOOTING,
    title: `Common payment issues and next steps`,
    summary: `Use this guide when a payment flow is blocked, unclear, or does not move forward as expected.`,
    category: HELP_GUIDE_CATEGORY.PAYMENTS,
    feature: HELP_GUIDE_FEATURE.PAYMENTS,
    audienceState: HELP_AUDIENCE_STATE.AUTHENTICATED,
    routeAffinity: [`/payments`, `/payments/[paymentRequestId]`],
    order: 40,
    prerequisites: [
      `Open the payment you need to review so you can compare the guide with the current state in the app.`,
    ],
    relatedGuides: [
      HELP_GUIDE_SLUG.PAYMENTS_OVERVIEW,
      HELP_GUIDE_SLUG.PAYMENTS_STATUSES,
      HELP_GUIDE_SLUG.PAYMENTS_CREATE_REQUEST,
      HELP_GUIDE_SLUG.PAYMENTS_START_PAYMENT,
    ],
  },
] as const satisfies readonly HelpGuideDefinition<HelpGuideSlug>[];
