export const CHECK_PATHS = [
  `apps/admin-v2/src/app`,
  `apps/admin-v2/src/lib/admin-mutations.server.ts`,
  `apps/api-v2/src/admin-v2`,
  `apps/api-v2/src/shared/admin-action-audit.service.ts`,
  `apps/api-v2/src/auth/jwt.strategy.ts`,
  `apps/api-v2/src/auth/jwt.guard.ts`,
  `apps/api-v2/src/guards/auth.guard.ts`,
  `apps/api-v2/src/shared-common/csrf-protection.ts`,
  `apps/api-v2/src/shared/origin-resolver.service.ts`,
  `packages/api-types/src/http/admin-path.ts`,
  `packages/api-types/src/http/auth-cookie-policy.ts`,
  `admin-v2-pack/01-foundation-and-invariants.md`,
  `admin-v2-pack/03-platform-auth-rbac.md`,
  `admin-v2-pack/05-financial-workspaces.md`,
  `admin-v2-pack/07-backend-contracts-and-data-plan.md`,
  `admin-v2-pack/08-rollout-risks-and-sequencing.md`,
  `docs/admin-v2-mvp-2-rbac-prerequisite.md`,
  `docs/admin-v2-mvp-3-anomalies-first-slice.md`,
  `docs/admin-v2-mvp-3.1b-perf-evidence.md`,
  `docs/admin-v2-mvp-3.1c-anomaly-classes-expansion.md`,
  `docs/admin-v2-mvp-3.1c-perf-evidence.md`,
  `docs/admin-v2-mvp-3.2a-operational-assignments.md`,
  `docs/admin-v2-mvp-3.3a-saved-views-skeleton.md`,
  `docs/admin-v2-mvp-3.3b-operational-alerts-skeleton.md`,
  `docs/admin-v2-mvp-3.4a-verification-workspace-completion.md`,
  `docs/admin-v2-mvp-3.4b-system-alerts-verification-queue-section.md`,
  `docs/admin-v2-mvp-3.5a-admin-auth-hardening-plaintext-retirement.md`,
  `docs/admin-v2-mvp-3.5b-frontend-url-migration.md`,
  `docs/admin-v2-mvp-3.5c-legacy-controller-retirement.md`,
  `docs/admin-v2-mvp-3.5d-session-management-observability.md`,
  `docs/admin-v2-mvp-3.6a-operational-assignments-ledger-entry-activation.md`,
  `docs/admin-v2-mvp-3.6b-operational-assignments-payment-request-activation-with-extraction.md`,
  `docs/admin-v2-mvp-3.6c-operational-assignments-payout-activation.md`,
  `docs/admin-v2-mvp-3.6d-operational-assignments-document-activation.md`,
  `docs/admin-v2-mvp-3.6e-operational-assignments-fx-conversion-activation.md`,
  `docs/admin-v2-mvp-3.7a-list-surface-assignee-fx-conversion.md`,
  `docs/admin-v2-mvp-3.7b-list-surface-assignee-document-with-extraction.md`,
  `docs/admin-v2-mvp-3.7c-list-surface-assignee-payments-operations.md`,
  `docs/admin-v2-mvp-3.7d-pre-perf-operational-assignment-active-lookup-index-audit.md`,
  `docs/admin-v2-slice-patch-platform-hygiene-bundle.md`,
  `apps/admin-v2/src/components/assignment-card.tsx`,
  `apps/api-v2/src/admin/auth/admin-auth-session-reasons.ts`,
  `packages/database-2/prisma/migrations/20260420191500_admin_v2_duplicate_idempotency_risk_index/README.md`,
  `packages/database-2/prisma/migrations/20260421100000_admin_v2_saved_views_foundation/README.md`,
  `packages/database-2/prisma/migrations/20260421100500_admin_v2_operational_alerts_foundation/README.md`,
  `packages/database-2/prisma/migrations/20260421101000_admin_v2_verification_queue_workspace/README.md`,
  `packages/database-2/prisma/migrations/20260421110000_admin_auth_session_invalidated_reason_check/README.md`,
  `packages/database-2/prisma/migrations/20260421110500_admin_v2_auth_refresh_reuse_workspace/README.md`,
];

export const AUDIT_ACTIONS = [
  `consumer_note_create`,
  `consumer_flag_add`,
  `consumer_flag_remove`,
  `consumer_force_logout`,
  `consumer_suspend`,
  `consumer_email_resend`,
  `verification_approve`,
  `verification_reject`,
  `payment_method_disable`,
  `payment_method_remove_default`,
  `payment_method_duplicate_escalate`,
  `payout_escalate`,
  `exchange_rate_approve`,
  `exchange_rule_pause`,
  `exchange_rule_resume`,
  `exchange_rule_run_now`,
  `exchange_scheduled_force_execute`,
  `exchange_scheduled_cancel`,
  `document_tag_create`,
  `document_tag_update`,
  `document_tag_delete`,
  `document_retag`,
  `document_bulk_tag`,
  `admin_invite`,
  `admin_deactivate`,
  `admin_restore`,
  `admin_role_change`,
  `admin_permissions_change`,
  `admin_password_reset`,
  `admin_session_revoke`,
  `admin_session_revoke_other`,
  `assignment_claim`,
  `assignment_release`,
  `assignment_reassign`,
  `saved_view_create`,
  `saved_view_update`,
  `saved_view_delete`,
  `alert_create`,
  `alert_update`,
  `alert_delete`,
];

export const CAPABILITIES = [
  `me.read`,
  `overview.read`,
  `consumers.read`,
  `consumers.notes`,
  `consumers.flags`,
  `consumers.force_logout`,
  `consumers.suspend`,
  `consumers.email_resend`,
  `verification.read`,
  `verification.decide`,
  `payments.read`,
  `ledger.read`,
  `ledger.anomalies`,
  `audit.read`,
  `exchange.read`,
  `exchange.manage`,
  `documents.read`,
  `documents.manage`,
  `admins.read`,
  `admins.manage`,
  `payment_methods.read`,
  `payment_methods.manage`,
  `payouts.escalate`,
  `system.read`,
  `assignments.manage`,
  `saved_views.manage`,
  `alerts.manage`,
];

export const FRONTEND_ACTIONS = [
  `disablePaymentMethodAction`,
  `removeDefaultPaymentMethodAction`,
  `escalateDuplicatePaymentMethodAction`,
  `approveExchangeRateAction`,
  `pauseExchangeRuleAction`,
  `resumeExchangeRuleAction`,
  `runExchangeRuleNowAction`,
  `forceExecuteScheduledExchangeAction`,
  `cancelScheduledExchangeAction`,
  `createDocumentTagAction`,
  `updateDocumentTagAction`,
  `deleteDocumentTagAction`,
  `retagDocumentAction`,
  `bulkTagDocumentsAction`,
  `inviteAdminAction`,
  `deactivateAdminAction`,
  `restoreAdminAction`,
  `changeAdminRoleAction`,
  `changeAdminPermissionsAction`,
  `resetAdminPasswordAction`,
  `claimVerificationAssignmentAction`,
  `releaseVerificationAssignmentAction`,
  `reassignVerificationAssignmentAction`,
  `claimLedgerEntryAssignmentAction`,
  `releaseLedgerEntryAssignmentAction`,
  `reassignLedgerEntryAssignmentAction`,
  `claimPaymentRequestAssignmentAction`,
  `releasePaymentRequestAssignmentAction`,
  `reassignPaymentRequestAssignmentAction`,
  `claimPayoutAssignmentAction`,
  `releasePayoutAssignmentAction`,
  `reassignPayoutAssignmentAction`,
  `claimDocumentAssignmentAction`,
  `releaseDocumentAssignmentAction`,
  `reassignDocumentAssignmentAction`,
  `claimFxConversionAssignmentAction`,
  `releaseFxConversionAssignmentAction`,
  `reassignFxConversionAssignmentAction`,
  `createSavedViewAction`,
  `updateSavedViewAction`,
  `deleteSavedViewAction`,
  `createOperationalAlertAction`,
  `updateOperationalAlertAction`,
  `deleteOperationalAlertAction`,
  `revokeMyAdminSessionAction`,
  `revokeAdminSessionAction`,
];

export const ROUTE_TOKENS = {
  'apps/api-v2/src/admin-v2/admins/admin-v2-admins.controller.ts': [
    '@Post(`invite`)',
    '@Post(`:id/deactivate`)',
    '@Post(`:id/restore`)',
    '@Post(`:id/role-change`)',
    '@Post(`:id/permissions-change`)',
    '@Post(`:id/password-reset`)',
    '@Get(`:id/sessions`)',
    '@Post(`:id/sessions/:sessionId/revoke`)',
  ],
  'apps/api-v2/src/admin-v2/auth/admin-v2-auth.controller.ts': [
    '@Post(`revoke-session`)',
    '@Get(`me/sessions`)',
  ],
  'apps/api-v2/src/admin-v2/payment-methods/admin-v2-payment-methods.controller.ts': [
    '@Post(`:id/disable`)',
    '@Post(`:id/remove-default`)',
    '@Post(`:id/duplicate-escalate`)',
  ],
  'apps/api-v2/src/admin-v2/exchange/admin-v2-exchange.controller.ts': [
    '@Post(`rates/:id/approve`)',
    '@Post(`rules/:id/pause`)',
    '@Post(`rules/:id/resume`)',
    '@Post(`rules/:id/run-now`)',
    '@Post(`scheduled/:id/force-execute`)',
    '@Post(`scheduled/:id/cancel`)',
  ],
  'apps/api-v2/src/admin-v2/documents/admin-v2-documents.controller.ts': [
    '@Post(`tags`)',
    '@Patch(`tags/:id`)',
    '@Delete(`tags/:id`)',
    '@Post(`:id/retag`)',
    '@Post(`bulk-tag`)',
  ],
  'apps/api-v2/src/admin-v2/payouts/admin-v2-payouts.controller.ts': ['@Post(`:id/escalate`)'],
  'apps/api-v2/src/admin-v2/assignments/admin-v2-assignments.controller.ts': [
    '@Post(`claim`)',
    '@Post(`release`)',
    '@Post(`reassign`)',
  ],
  'apps/api-v2/src/admin-v2/saved-views/admin-v2-saved-views.controller.ts': [
    '@Get()',
    '@Post()',
    '@Patch(`:savedViewId`)',
    '@Delete(`:savedViewId`)',
  ],
  'apps/api-v2/src/admin-v2/operational-alerts/admin-v2-operational-alerts.controller.ts': [
    '@Get()',
    '@Post()',
    '@Patch(`:operationalAlertId`)',
    '@Delete(`:operationalAlertId`)',
  ],
};

export const ROOT_SCRIPTS = {
  'verify:admin-v2-gates': `node ./scripts/admin-v2-gates/verify.mjs`,
  'test:admin-v2': `yarn workspace @remoola/api-v2 run test --testPathPatterns='admin-v2'`,
};

export const AFFECTED_PATHS = [
  `apps/admin-v2/`,
  `apps/api-v2/src/admin-v2/`,
  `apps/api-v2/src/shared/admin-action-audit.service.ts`,
  `apps/api-v2/src/auth/jwt.strategy.ts`,
  `apps/api-v2/src/auth/jwt.guard.ts`,
  `apps/api-v2/src/guards/auth.guard.ts`,
  `apps/api-v2/src/shared-common/csrf-protection.ts`,
  `apps/api-v2/src/shared/origin-resolver.service.ts`,
  `packages/api-types/src/http/admin-path.ts`,
  `packages/api-types/src/http/auth-cookie-policy.ts`,
  `packages/database-2/prisma/schema.prisma`,
  `packages/database-2/prisma/migrations/`,
  `admin-v2-pack/01-foundation-and-invariants.md`,
  `admin-v2-pack/03-platform-auth-rbac.md`,
  `admin-v2-pack/05-financial-workspaces.md`,
  `admin-v2-pack/07-backend-contracts-and-data-plan.md`,
  `admin-v2-pack/08-rollout-risks-and-sequencing.md`,
  `docs/admin-v2-merge-gates.md`,
  `docs/admin-v2-mvp-2-rbac-prerequisite.md`,
  `docs/admin-v2-mvp-3-anomalies-first-slice.md`,
  `docs/admin-v2-mvp-3.1c-anomaly-classes-expansion.md`,
  `docs/admin-v2-mvp-3.1c-perf-evidence.md`,
  `docs/admin-v2-mvp-3.5d-session-management-observability.md`,
  `apps/api-v2/src/admin/auth/admin-auth-session-reasons.ts`,
  `.husky/pre-commit`,
  `package.json`,
  `scripts/admin-v2-gates/`,
];

export const OLD_DOC_TOKENS = [
  `audit-vocabulary-completeness`,
  `transaction-matrix-coverage`,
  `side-effects-map-coverage`,
  `rbac-capability-mapping-completeness`,
  `phase-control-matrix-completeness`,
  `deferred-feature-activation`,
  `nav-tier-promotion-guard`,
  `nav-audit-and-cross-link`,
  `taxonomy-completeness`,
  `sla-escalation-tuple`,
  `dead-end-case-pages`,
  `scripts/admin-v2-gates/allowlist/`,
  `allowlist.self-test.mjs`,
];

export const RECONCILIATION_NOTES = {
  'docs/admin-v2-mvp-2-rbac-prerequisite.md': [
    `schema-backed RBAC primitives уже landed`,
    `\`admins.manage\` уже используется как live capability boundary`,
    `MVP-3 maturity`,
  ],
  'admin-v2-pack/05-financial-workspaces.md': [
    `Current codebase reading`,
    `detail surface уже несет capability-gated write controls`,
  ],
  'admin-v2-pack/08-rollout-risks-and-sequencing.md': [
    `Sequence 6`,
    `ledger anomalies`,
    `current runtime already includes the writes that this kickoff slice used to exclude`,
  ],
  'docs/admin-v2-mvp-3-anomalies-first-slice.md': [
    `Sequence 6`,
    `first maturity slice`,
    `three classes`,
    `temporarily-unavailable`,
    `no new audit actions`,
    `Finding: outcome→entry sync trigger absence`,
    `Decision: largeValueOutliers currency coverage`,
    `INCONSISTENT_CHAIN_GRACE_MINUTES`,
    `11 major/reserve currencies`,
    `admin-v2-mvp-3.1b-perf-evidence.md`,
    `admin-v2-mvp-3.1c-anomaly-classes-expansion.md`,
  ],
  'docs/admin-v2-mvp-3.1b-perf-evidence.md': [
    `EXPLAIN ANALYZE`,
    `p95`,
    `summary endpoint budget`,
    `index reshape rationale`,
    `Promise.all decision`,
    `idx_ledger_entry_outcome_lateral_covering`,
    `20260420170000_admin_v2_anomalies_outcome_indexes`,
  ],
  'docs/admin-v2-mvp-3.1c-anomaly-classes-expansion.md': [
    `Sequence 6`,
    `classes expansion`,
    `six classes`,
    `temporarily-unavailable`,
    `no new audit actions`,
    `Decision: duplicateIdempotencyRisk redefinition`,
    `Decision: impossibleTransitions terminal-only scope`,
    `Decision: orphanedEntries definition`,
    `ORPHANED_ENTRY_GRACE_HOURS`,
    `TERMINAL_OUTCOME_STATUSES`,
    `admin-v2-mvp-3.1b-perf-evidence.md`,
  ],
  'docs/admin-v2-mvp-3.1c-perf-evidence.md': [
    `EXPLAIN ANALYZE`,
    `p95`,
    `summary endpoint budget`,
    `six-class summary`,
    `orphanedEntries`,
    `duplicateIdempotencyRisk`,
    `impossibleTransitions`,
    `Seq Scan justification`,
  ],
  'docs/admin-v2-mvp-3.2a-operational-assignments.md': [
    `MVP-3.2a`,
    `Sequence 6`,
    `assignments.manage`,
    `assignment_claim`,
    `assignment_release`,
    `assignment_reassign`,
    `OperationalAssignmentModel`,
    `verification only`,
    `single active assignment per resource`,
    `append-only assignment chain`,
    `no new schema migrations`,
    `Decision: resourceType allowlist verification only`,
    `Decision: capability granularity single`,
    `Decision: reassign requires SUPER_ADMIN`,
    `Decision: version check via expectedReleasedAtNull`,
  ],
  'docs/admin-v2-mvp-3.3a-saved-views-skeleton.md': [
    `MVP-3.3a`,
    `Sequence 6`,
    `saved_views.manage`,
    `saved_view_create`,
    `saved_view_update`,
    `saved_view_delete`,
    `SavedViewModel`,
    `ledger_anomalies only`,
    `personal-only ownership`,
    `soft-delete`,
    `opaque queryPayload`,
    `single workspace allowlist`,
    `Decision: workspace allowlist ledger_anomalies only`,
    `Decision: opaque queryPayload contract`,
    `Decision: personal-only ownership`,
    `Decision: soft-delete by default`,
    `Decision: name unique partial index`,
    `MAX_SAVED_VIEW_PAYLOAD_BYTES`,
    `expectedDeletedAtNull`,
  ],
  'docs/admin-v2-mvp-3.3b-operational-alerts-skeleton.md': [
    `MVP-3.3b`,
    `Sequence 7`,
    `alerts.manage`,
    `alert_create`,
    `alert_update`,
    `alert_delete`,
    `OperationalAlertModel`,
    `ledger_anomalies only`,
    `count_gt only`,
    `personal-only ownership`,
    `soft-delete`,
    `opaque queryPayload`,
    `structured thresholdPayload`,
    `single workspace allowlist`,
    `@Cron`,
    `EVALUATOR_TICK_MAX_ALERTS`,
    `EVALUATOR_PER_ALERT_TIMEOUT_MS`,
    `last_fired_at`,
    `last_evaluation_error`,
    `Decision: workspace allowlist ledger_anomalies only`,
    `Decision: separate query and threshold payloads`,
    `Decision: threshold count_gt only`,
    `Decision: in-app delivery only`,
    `Decision: no occurrence model in skeleton`,
    `Decision: no audit on fire`,
    `Decision: no confirmation on mutations`,
    `Decision: evaluation state reset on definition change`,
    `Decision: workspace immutable on update`,
    `Decision: no manual re-evaluate endpoint`,
    `Decision: workspace evaluator strategy boundary`,
    `Decision: defer link from system page`,
    `MVP-3 maturity track closed`,
    `expectedDeletedAtNull`,
    `Deviation from §1.20`,
    `getCount`,
    `AdminV2LedgerAnomaliesService.getCount`,
    `anomaly cluster read-only addition`,
    `workspace-evaluator-vs-domain-cluster boundary`,
  ],
  'docs/admin-v2-mvp-3.4a-verification-workspace-completion.md': [
    `MVP-3.4a`,
    `Sequence 6`,
    `verification_queue workspace`,
    `workspace allowlist expansion`,
    `VerificationQueueAlertEvaluator`,
    `getQueueCount`,
    `§15 blessed deviation: verification cluster getQueueCount addition`,
    `additive ALTER CHECK migration`,
    `no new capability`,
    `no new audit action`,
    `no new endpoint`,
    `frontend-only filters`,
    `Decision: ALTER CHECK over rename strategy`,
    `Decision: getQueueCount excludes missingProfileData / missingDocuments`,
    `Decision: separate evaluator file per workspace`,
    `Decision: shared single capability per domain preserved`,
    `Decision: workspace immutable post-create preserved`,
  ],
  'docs/admin-v2-mvp-3.4b-system-alerts-verification-queue-section.md': [
    `MVP-3.4b`,
    `Sequence 6`,
    `verification_queue alerts UI`,
    `OperationalAlertsPage third section`,
    `CreateVerificationQueueAlertForm`,
    `parseVerificationQueueQuery`,
    `describeQueryPayload verification_queue branch`,
    `no backend change`,
    `no allowlist change`,
    `no migration`,
    `no new capability`,
    `no new audit action`,
    `default queryPayload {}`,
    `frontend-only filters disclaimer mirrored from /verification`,
    `Decision: sibling create-form, not parametric refactor`,
    `Decision: default queryPayload is empty (total queue baseline)`,
    `Decision: no fired-state indicator on /verification`,
    `Closes 3.4a §1.22 deferral`,
  ],
  'docs/admin-v2-mvp-3.5a-admin-auth-hardening-plaintext-retirement.md': [
    `MVP-3.5a`,
    `Risk 13`,
    `auth hardening`,
    `plaintext fallback retirement`,
    `AdminAuthSessionModel`,
    `AccessRefreshTokenModel`,
    `getLegacyAccessAndRefreshToken removed`,
    `findIdentityAccess removed`,
    `admin_session_revoke audit`,
    `dual audit (logout + admin_session_revoke)`,
    `no schema migration`,
    `no new capability`,
    `no new auth audit event`,
    `forced re-login for residual non-sid admin tokens`,
    `legacy AdminAuthController retained (slice 3.5c)`,
    `frontend URL migration deferred (slice 3.5b)`,
    `session observability deferred (slice 3.5d)`,
    `Decision: sid mandatory on admin path`,
    `Decision: no enum revoke_reason in this slice`,
    `Decision: dual-audit not replacement`,
    `Decision: no capability gate on revoke-session`,
  ],
  'docs/admin-v2-mvp-3.5b-frontend-url-migration.md': [
    `MVP-3.5b`,
    `Risk 13`,
    `frontend URL migration`,
    `BFF folder rename`,
    `/api/admin/auth/* removed from admin-v2 frontend`,
    `/api/admin-v2/auth/* adopted on admin-v2 frontend`,
    `refresh path renamed refresh to refresh-access`,
    `LoginForm.tsx migrated`,
    `middleware.ts REFRESH_PATH migrated`,
    `accept-invite page migrated`,
    `reset-password page migrated`,
    `BFF route files relocated via git mv`,
    `no backend changes`,
    `no schema migration`,
    `no new capability`,
    `no new audit action`,
    `no new endpoint`,
    `no new DTO`,
    `cookie keys unchanged`,
    `CSRF flow unchanged`,
    `request body unchanged`,
    `response shape unchanged`,
    `legacy AdminAuthController retained (slice 3.5c)`,
    `/api/me BFF retained as known cosmetic gap`,
    `/logout route retained as known cosmetic gap`,
    `Decision: clean rename without shim routes`,
    `Decision: refresh-access alignment with backend`,
    `Decision: scope strict per 3.5a §18.1`,
    `Decision: no /api/me migration in this slice`,
    `Clerical correction: 3.5a references (public) not (auth)`,
    `Old URLs return 404 after deploy`,
  ],
  'docs/admin-v2-mvp-3.5c-legacy-controller-retirement.md': [
    `MVP-3.5c`,
    `Risk 13`,
    `legacy AdminAuthController retirement`,
    `admin-auth.controller.ts deleted`,
    `admin-auth.controller.spec.ts deleted`,
    `admin.module.ts controllers field removed`,
    `AdminAuthController unregistered from AdminModule`,
    `/api/admin/auth/* removed from api-v2 backend`,
    `/api/admin-v2/auth/* sole admin auth surface in api-v2`,
    `admin-auth-lifecycle.e2e-spec migrated`,
    `admin-step-up.e2e-spec login mechanism migrated`,
    `admin-payment-reversal.e2e-spec login mechanism migrated`,
    `jwt.strategy.spec fixture migrated`,
    `consumer-action.interceptor.spec fixture migrated`,
    `swagger-cookie-auth description literals migrated`,
    `swagger-cookie-auth.spec assertions migrated`,
    `apps/api-v2/README.md migrated`,
    `AdminAuthService retained (shared with admin-v2)`,
    `AdminAuthModule retained (provides AdminAuthService to admin-v2)`,
    `AdminV2AuthController unchanged`,
    `Credentials DTO retained (used by admin-v2)`,
    `cookie helpers unchanged`,
    `CSRF flow unchanged`,
    `request body unchanged`,
    `response shape unchanged`,
    `no schema migration`,
    `no new capability`,
    `no new audit action`,
    `no new endpoint`,
    `no new DTO`,
    `apps/api/ workspace frozen (separate retirement track)`,
    `apps/admin/ workspace frozen`,
    `apps/admin-v2/ frozen (already migrated in 3.5b)`,
    `Decision: production helpers tolerant via isAdminApiPath`,
    `Decision: SWAGGER_PROTECTED_PATH_PREFIXES_BY_AUDIENCE.admin retained at /api/admin/`,
    `Decision: controllers field removed not emptied`,
    `Decision: no shim routes for legacy /api/admin/auth/* in api-v2`,
    `Decision: AdminAuthService kept as shared admin-v2 dependency`,
    `Known dev-UX limitation: Swagger CSRF auto-mirror gap for /api/admin-v2/`,
    `Old api-v2 URLs return 404 after deploy`,
  ],
  'docs/admin-v2-mvp-3.5d-session-management-observability.md': [
    `MVP-3.5d`,
    `Risk 13`,
    `session-management observability`,
    `cross-admin revoke`,
    `invalidated_reason CHECK constraint`,
    `auth_refresh_reuse alert workspace`,
    `ADMIN_AUTH_SESSION_REVOKE_REASONS`,
    `admin_auth_session_invalidated_reason_check`,
    `admin_session_revoke_other`,
    `AdminV2AdminSessionsService`,
    `AuthRefreshReuseAlertEvaluator`,
    `GET /api/admin-v2/auth/me/sessions`,
    `GET /api/admin-v2/admins/:id/sessions`,
    `POST /api/admin-v2/admins/:id/sessions/:sessionId/revoke`,
    `403 Forbidden cross-actor guard`,
    `dual audit (logout + admin_session_revoke_other)`,
    `30-day retention cap`,
    `windowMinutes`,
    `count_gt`,
    `Decision: CHECK constraint over Postgres ENUM`,
    `Decision: cross-admin endpoint in AdminV2AdminsController`,
    `Decision: 403 deprecation over silent removal`,
    `Decision: AuthSessionModel.invalidatedReason consumer column untouched`,
    `Decision: separate evaluator file per workspace preserved`,
    `Decision: shared admin-auth-session-reasons.ts const`,
    `apps/api/ workspace frozen`,
    `apps/admin/ workspace frozen`,
    `apps/api-v2/src/consumer/ frozen`,
    `Risk 13 mitigation track closed`,
    `schema.prisma whitespace drift reverted`,
    `pre-existing \\_prisma_migrations drift on 20260420163000 and 20260420191500`,
  ],
  'docs/admin-v2-mvp-3.6a-operational-assignments-ledger-entry-activation.md': [
    `MVP-3.6a`,
    `operational assignments ledger_entry activation`,
    `ASSIGNABLE_RESOURCE_TYPES extension`,
    `'ledger_entry' resourceType activated`,
    `no new prisma migrations`,
    `no new capability`,
    `no new audit action`,
    `no new endpoint`,
    `reuse assignments.manage`,
    `reuse assignment_claim`,
    `reuse assignment_release`,
    `reuse assignment_reassign`,
    `reuse POST /admin-v2/assignments/{claim,release,reassign}`,
    `inline copy backend assignment-context query`,
    `inline copy UI Assignments card`,
    `claimLedgerEntryAssignmentAction`,
    `releaseLedgerEntryAssignmentAction`,
    `reassignLedgerEntryAssignmentAction`,
    `revalidateLedgerEntryAssignmentPaths`,
    `assignment context on /ledger/[ledgerEntryId] case page`,
    `anomalies list page unchanged`,
    `ledger list page unchanged`,
    `verification surface frozen`,
    `apps/api/ workspace frozen`,
    `apps/admin/ workspace frozen`,
    `apps/api-v2/src/consumer/ frozen`,
    `Decision: ledger_entry over ledger_anomaly resourceType`,
    `Decision: zero migration (DB CHECK already permits ledger_entry)`,
    `Decision: inline copy over shared helper extraction`,
    `Decision: anomalies-list assignment column out of scope`,
    `Decision: ledger-list assignment column out of scope`,
    `Decision: reuse assignment_* audit actions across resourceTypes`,
    `Decision: SUPER_ADMIN reassign requirement preserved`,
    `Decision: regulated decision controls preserved through reuse`,
    `Decision: F1 migration drift not absorbed`,
    `Known follow-up: Assignments aggregation SQL duplication`,
  ],
  'docs/admin-v2-mvp-3.6b-operational-assignments-payment-request-activation-with-extraction.md': [
    `MVP-3.6b`,
    `operational assignments payment_request activation`,
    `ASSIGNABLE_RESOURCE_TYPES extension`,
    `'payment_request' resourceType activated`,
    `no new prisma migrations`,
    `no new capability`,
    `no new audit action`,
    `no new endpoint`,
    `reuse assignments.manage`,
    `reuse assignment_claim`,
    `reuse assignment_release`,
    `reuse assignment_reassign`,
    `reuse POST /admin-v2/assignments/{claim,release,reassign}`,
    `shared backend helper getAssignmentContextForResource`,
    `shared frontend AssignmentCard component`,
    `claimPaymentRequestAssignmentAction`,
    `releasePaymentRequestAssignmentAction`,
    `reassignPaymentRequestAssignmentAction`,
    `revalidatePaymentRequestAssignmentPaths`,
    `assignment context on /payments/[paymentRequestId] case page`,
    `verification page refactored to AssignmentCard`,
    `ledger page refactored to AssignmentCard`,
    `payments list page unchanged`,
    `payments operations page unchanged`,
    `apps/api/ workspace frozen`,
    `apps/admin/ workspace frozen`,
    `apps/api-v2/src/consumer/ frozen`,
    `Decision: payment_request over payout / fx_conversion / document resourceType`,
    `Decision: zero migration (DB CHECK already permits payment_request)`,
    `Decision: shared helper extraction over inline copy`,
    `Decision: payments-list assignment column out of scope`,
    `Decision: reuse assignment_* audit actions across resourceTypes`,
    `Decision: SUPER_ADMIN reassign requirement preserved`,
    `Decision: regulated decision controls preserved through reuse`,
    `Decision: F1 migration drift not absorbed`,
    `Closed follow-up: Assignments aggregation SQL duplication`,
  ],
  'docs/admin-v2-mvp-3.6c-operational-assignments-payout-activation.md': [
    `MVP-3.6c`,
    `operational assignments payout activation`,
    `ASSIGNABLE_RESOURCE_TYPES extension`,
    `'payout' resourceType activated`,
    `no new prisma migrations`,
    `no new capability`,
    `no new audit action`,
    `no new endpoint`,
    `reuse assignments.manage`,
    `reuse assignment_claim`,
    `reuse assignment_release`,
    `reuse assignment_reassign`,
    `reuse POST /admin-v2/assignments/{claim,release,reassign}`,
    `reuse shared backend helper getAssignmentContextForResource`,
    `reuse shared frontend AssignmentCard component`,
    `claimPayoutAssignmentAction`,
    `releasePayoutAssignmentAction`,
    `reassignPayoutAssignmentAction`,
    `revalidatePayoutAssignmentPaths`,
    `assignment context on /payouts/[payoutId] case page`,
    `payouts list page unchanged`,
    `verification surface frozen`,
    `ledger surface frozen`,
    `payments surface frozen`,
    `escalatePayoutAction frozen`,
    `revalidatePayoutPaths frozen`,
    `payoutEscalation flow frozen`,
    `apps/api/ workspace frozen`,
    `apps/admin/ workspace frozen`,
    `apps/api-v2/src/consumer/ frozen`,
    `Decision: payout fourth resource type`,
    `Decision: PayoutEscalationModel domain ownership signal`,
    `Decision: zero migration (DB CHECK already permits payout)`,
    `Decision: consume shared helper (no extraction)`,
    `Decision: consume shared AssignmentCard (no component changes)`,
    `Decision: payouts list assignment column out of scope`,
    `Decision: reuse assignment_* audit actions across resourceTypes`,
    `Decision: SUPER_ADMIN reassign requirement preserved`,
    `Decision: regulated decision controls preserved through reuse`,
    `Decision: assignment orthogonal to payoutEscalation classification`,
    `Decision: F1 migration drift not absorbed`,
    `Decision: prisma format whitespace drift not absorbed`,
  ],
  'docs/admin-v2-mvp-3.6d-operational-assignments-document-activation.md': [
    `MVP-3.6d`,
    `operational assignments document activation`,
    `ASSIGNABLE_RESOURCE_TYPES extension`,
    `'document' resourceType activated`,
    `no new prisma migrations`,
    `no new capability`,
    `no new audit action`,
    `no new endpoint`,
    `reuse assignments.manage`,
    `reuse assignment_claim`,
    `reuse assignment_release`,
    `reuse assignment_reassign`,
    `reuse POST /admin-v2/assignments/{claim,release,reassign}`,
    `reuse shared backend helper getAssignmentContextForResource`,
    `reuse shared frontend AssignmentCard component`,
    `claimDocumentAssignmentAction`,
    `releaseDocumentAssignmentAction`,
    `reassignDocumentAssignmentAction`,
    `revalidateDocumentAssignmentPaths`,
    `assignment context on /documents/[documentId] case page`,
    `documents list page unchanged`,
    `documents tags page unchanged`,
    `verification surface frozen`,
    `ledger surface frozen`,
    `payments surface frozen`,
    `payouts surface frozen`,
    `retagDocumentAction frozen`,
    `bulkTagDocumentsAction frozen`,
    `apps/api/ workspace frozen`,
    `apps/admin/ workspace frozen`,
    `apps/api-v2/src/consumer/ frozen`,
    `Decision: document fifth resource type`,
    `Decision: zero migration (DB CHECK already permits document)`,
    `Decision: consume shared helper (no extraction)`,
    `Decision: consume shared AssignmentCard (no component changes)`,
    `Decision: documents list assignment column out of scope`,
    `Decision: tags page out of scope`,
    `Decision: reuse assignment_* audit actions across resourceTypes`,
    `Decision: SUPER_ADMIN reassign requirement preserved`,
    `Decision: regulated decision controls preserved through reuse`,
    `Decision: narrow revalidate helper (documents list + case only)`,
    `Decision: AdminV2DocumentsModule.exports unchanged`,
    `Decision: F1 migration drift not absorbed`,
    `Decision: prisma format whitespace drift not absorbed`,
  ],
  'docs/admin-v2-mvp-3.6e-operational-assignments-fx-conversion-activation.md': [
    `MVP-3.6e`,
    `operational assignments fx_conversion activation`,
    `ASSIGNABLE_RESOURCE_TYPES extension`,
    `'fx_conversion' resourceType activated`,
    `no new prisma migrations`,
    `no new capability`,
    `no new audit action`,
    `no new endpoint`,
    `reuse assignments.manage`,
    `reuse assignment_claim`,
    `reuse assignment_release`,
    `reuse assignment_reassign`,
    `reuse POST /admin-v2/assignments/{claim,release,reassign}`,
    `reuse shared backend helper getAssignmentContextForResource`,
    `reuse shared frontend AssignmentCard component`,
    `claimFxConversionAssignmentAction`,
    `releaseFxConversionAssignmentAction`,
    `reassignFxConversionAssignmentAction`,
    `revalidateFxConversionAssignmentPaths`,
    `assignment context on /exchange/scheduled/[conversionId] case page`,
    `exchange scheduled list page unchanged`,
    `exchange rates pages unchanged`,
    `exchange rules pages unchanged`,
    `force-execute scheduled flow unchanged`,
    `cancel scheduled flow unchanged`,
    `verification surface frozen`,
    `ledger surface frozen`,
    `payments surface frozen`,
    `payouts surface frozen`,
    `documents surface frozen`,
    `forceExecuteScheduledExchangeAction frozen`,
    `cancelScheduledExchangeAction frozen`,
    `approveExchangeRateAction frozen`,
    `pauseExchangeRuleAction frozen`,
    `resumeExchangeRuleAction frozen`,
    `runExchangeRuleNowAction frozen`,
    `apps/api/ workspace frozen`,
    `apps/admin/ workspace frozen`,
    `apps/api-v2/src/consumer/ frozen`,
    `Decision: fx_conversion sixth resource type`,
    `Decision: pure consumer slice mirror 3.6d`,
    `Decision: zero migration (DB CHECK already permits fx_conversion)`,
    `Decision: consume shared helper (no extraction)`,
    `Decision: consume shared AssignmentCard (no component changes)`,
    `Decision: exchange scheduled list assignment column out of scope`,
    `Decision: reuse assignment_* audit actions across resourceTypes`,
    `Decision: SUPER_ADMIN reassign requirement preserved`,
    `Decision: regulated decision controls preserved through reuse`,
    `Decision: assignment orthogonal to force-execute scheduled mutation`,
    `Decision: assignment orthogonal to cancel scheduled mutation`,
    `Decision: assignment orthogonal to rate approval`,
    `Decision: assignment orthogonal to rule lifecycle`,
    `Decision: narrow revalidate helper (exchange/scheduled list + case only)`,
    `Decision: AdminV2ExchangeModule.exports unchanged`,
    `Decision: literal fx_conversion generic but admin-v2 activation scope narrow to ScheduledFxConversionModel`,
    `Decision: factory pattern spec extension (single createService site, lower churn)`,
    `Decision: 54.2KB exchange-service scope guard`,
    `Decision: consumer deferred for cross-context coupling`,
    `Decision: F1 migration drift not absorbed`,
    `Decision: prisma format whitespace drift not absorbed`,
  ],
  'docs/admin-v2-mvp-3.7a-list-surface-assignee-fx-conversion.md': [
    `MVP-3.7a`,
    `list-surface assignee column`,
    `exchange scheduled list page`,
    `'fx_conversion' resourceType list extension`,
    `no new prisma migrations`,
    `no new capability`,
    `no new audit action`,
    `no new endpoint`,
    `no new DTO`,
    `additive ExchangeScheduledListResponse field`,
    `assignedTo field appended last`,
    `inline copy bulk getActiveAssignees`,
    `private getActiveAssignees in AdminV2ExchangeService`,
    `verification surface frozen`,
    `AdminV2AssignmentsService public surface unchanged`,
    `54.2KB exchange-service scope guard`,
    `≤25 LOC additive scope guard preserved`,
    `single-table render mode (no responsive triple-render touched)`,
    `documents list assignment column out of scope`,
    `payouts list assignment column out of scope`,
    `payments list assignment column out of scope`,
    `payments operations list assignment column out of scope`,
    `ledger list assignment column out of scope`,
    `ledger anomalies list assignment column out of scope`,
    `assignee filter out of scope`,
    `assignee sort out of scope`,
    `claim from list affordance out of scope`,
    `apps/api/ workspace frozen`,
    `apps/admin/ workspace frozen`,
    `apps/api-v2/src/consumer/ workspace frozen`,
    `Decision: inline copy over shared helper extraction`,
    `Decision: bulk helper extraction trigger deferred to third consumer`,
    `Decision: AdminV2VerificationService.getActiveAssignees not refactored`,
    `Decision: assignedTo appended last to items shape`,
    `Decision: exchange/scheduled chosen as safest single-table list page`,
    `Decision: payments/ledger deferred for responsive triple-render risk class`,
    `Decision: payouts/payments-operations deferred for bucket-of-cards layout (no column slot)`,
    `Decision: documents deferred to follow extraction trigger`,
    `Decision: F1 migration drift not absorbed`,
    `Decision: prisma format whitespace drift not absorbed`,
  ],
  'docs/admin-v2-mvp-3.7b-list-surface-assignee-document-with-extraction.md': [
    `MVP-3.7b`,
    `list-surface assignee column`,
    `documents list page`,
    `'document' resourceType list extension`,
    `bulk helper extraction`,
    `getActiveAssigneesForResource`,
    `AdminV2AssignmentsService public surface widened by one method`,
    `verification inline getActiveAssignees removed`,
    `exchange inline getActiveAssignees removed`,
    `verification + exchange refactored to consume shared bulk helper`,
    `no new prisma migrations`,
    `no new capability`,
    `no new audit action`,
    `no new endpoint`,
    `no new DTO`,
    `additive DocumentsListResponse field`,
    `assignedTo field appended last`,
    `documents list column placed between Owners and Tags`,
    `54.2KB exchange-service scope guard preserved`,
    `single-table render mode (no responsive triple-render touched)`,
    `payouts list assignment column out of scope`,
    `payments list assignment column out of scope`,
    `payments operations list assignment column out of scope`,
    `ledger list assignment column out of scope`,
    `ledger anomalies list assignment column out of scope`,
    `documents tags page out of scope`,
    `assignee filter out of scope`,
    `assignee sort out of scope`,
    `claim from list affordance out of scope`,
    `apps/api/ workspace frozen`,
    `apps/admin/ workspace frozen`,
    `apps/api-v2/src/consumer/ workspace frozen`,
    `Decision: shared bulk helper extraction over third inline copy`,
    `Decision: parameterise on resourceType (canonical getAssignmentContextForResource precedent)`,
    `Decision: documents column placement between Owners and Tags`,
    `Decision: assignedTo appended last to items shape`,
    `Decision: documents chosen as second-safest single-table list page`,
    `Decision: payments/ledger/ledger-anomalies deferred for responsive triple-render risk class`,
    `Decision: payouts/payments-operations deferred for bucket-of-cards layout (no column slot)`,
    `Decision: sequential-after-findMany lookup (input depends on findMany ids)`,
    `Decision: F1 migration drift not absorbed`,
    `Decision: prisma format whitespace drift not absorbed`,
    `Closed follow-up: documents list assignment column`,
    `Closed follow-up: bulk helper extraction trigger deferred to third consumer`,
  ],
  'docs/admin-v2-mvp-3.7c-list-surface-assignee-payments-operations.md': [
    `MVP-3.7c`,
    `list-surface assignee surfacing`,
    `payment operations queue page`,
    `bucket-of-cards rendering family`,
    `'payment_request' resourceType list extension`,
    `getActiveAssigneesForResource shared bulk helper consumed`,
    `single bulk call per request`,
    `deduplicated resourceIds via Set`,
    `sequential-after-Promise.all lookup`,
    `mapPaymentOperationsQueueItem extended with optional assignedTo parameter`,
    `assignedTo field appended last`,
    `additive PaymentOperationsQueueResponse field`,
    `no new prisma migrations`,
    `no new capability`,
    `no new audit action`,
    `no new endpoint`,
    `no new DTO`,
    `no new helper extraction`,
    `no inline copy of bulk helper`,
    `card body assignee line placed after Due / Updated / Freshness`,
    `payouts list assignment surfacing out of scope`,
    `payments list assignment column out of scope`,
    `ledger list assignment column out of scope`,
    `ledger anomalies list assignment column out of scope`,
    `assignee filter out of scope`,
    `assignee sort out of scope`,
    `claim from list affordance out of scope`,
    `performance index audit on operational_assignment(resource_type, resource_id, released_at) flagged as immediate-horizon follow-up`,
    `apps/api/ workspace frozen`,
    `apps/admin/ workspace frozen`,
    `apps/api-v2/src/consumer/ workspace frozen`,
    `apps/api-v2/src/admin-v2/assignments/ frozen (helper consumed not modified)`,
    `Decision: bucket-of-cards renders assignee as one extra muted line not a pseudo-column`,
    `Decision: single bulk call with deduplicated resourceIds Set`,
    `Decision: thread assignee via mapPaymentOperationsQueueItem optional parameter`,
    `Decision: spec-test boundary one new behavioural test plus minimum fixture-fix`,
    `Decision: payouts not absorbed remains separate 3.7d-candidate slice`,
    `Decision: assignee placement at end of card body after Due / Updated / Freshness`,
    `Closed follow-up: payments operations list assignment column`,
  ],
  'docs/admin-v2-mvp-3.7d-pre-perf-operational-assignment-active-lookup-index-audit.md': [
    `SLICE-PATCH operational_assignment active-lookup index audit`,
    `bulk getActiveAssigneesForResource predicate`,
    `single-resource getAssignmentContextForResource active-row predicate`,
    `idx_operational_assignment_active_resource partial unique candidate`,
    `operational_assignment_resource_type_resource_id_released_at_idx full composite candidate`,
    `EXPLAIN (ANALYZE, BUFFERS) captured per cardinality bucket`,
    `local dev seed scale evidence`,
    `production re-baseline due before sixth bulk consumer or one order-of-magnitude row-count growth`,
    `four list-surface consumers as of SLICE-MVP-3.7c`,
    `six case-page consumers as of SLICE-MVP-3.6e`,
    `no service code change`,
    `no DTO change`,
    `no capability change`,
    `no audit action change`,
    `no endpoint change`,
    `Closed follow-up: performance index audit on operational_assignment(resource_type, resource_id, released_at)`,
    `apps/api/ workspace frozen`,
    `apps/admin/ workspace frozen`,
    `apps/api-v2/src/consumer/ workspace frozen`,
    `apps/api-v2/src/admin-v2/assignments/ frozen (subject query consumed not modified)`,
    `Decision: subject-query scope is exactly two active-row predicates`,
    `Decision: do not pre-declare existing partial unique in schema.prisma`,
    `Decision: local dev DB only with explicit production-re-baseline framing`,
    `Decision: binary audit outcome under one of two Decision headings`,
    `Decision: payouts list-surface assignee slice (3.7d) unblocked but not absorbed`,
    `Decision (a): Existing indexes are sufficient — no new migration`,
    `Deviation: handoff-README LANDED-move skipped`,
  ],
  'docs/admin-v2-slice-patch-platform-hygiene-bundle.md': [
    `SLICE-PATCH`,
    `platform hygiene bundle`,
    `prisma format baseline restore`,
    `F1 migration drift restore`,
    `30-day session retention test gap`,
    `Fragment A: prisma format`,
    `Fragment B: prisma migrate status`,
    `Fragment C: listSessionsForAdmin observable assertion`,
    `no behavior change`,
    `no new prisma migration`,
    `no new capability`,
    `no new audit action`,
    `no new endpoint`,
    `no schema change`,
    `whitespace-only schema.prisma diff`,
    `migration drift resolved via semantic equivalence verification`,
    `pre-commit prisma format check`,
    `pre-commit prisma migrate status check`,
    `verify:prisma-format script`,
    `verify:prisma-migrate-status script`,
    `apps/api/ workspace frozen`,
    `apps/admin/ workspace frozen`,
    `apps/admin-v2/ frozen`,
    `apps/api-v2/src/admin-v2/ frozen`,
    `apps/api-v2/src/consumer/ frozen`,
    `apps/api-v2/src/auth/ frozen`,
    `packages/api-types/ frozen`,
    `admin-v2-pack/ frozen`,
    `Decision: bundle three independent fragments`,
    `Decision: semantic equivalence verification over file edit`,
    `Decision: complementary observable test over duplication`,
    `Decision: scope-gated pre-commit checks`,
    `Decision: opt-out flags via env`,
    `Closed follow-up: prisma format baseline restore`,
    `Closed follow-up: pre-existing migration drift`,
    `Closed follow-up: 30-day retention cap test gap on AdminAuthService.listAdminSessions`,
  ],
};
