export const CHECK_PATHS = [
  `apps/admin-v2/src/app`,
  `apps/admin-v2/src/lib/admin-mutations.server.ts`,
  `apps/api-v2/src/admin-v2`,
  `apps/api-v2/src/shared/admin-action-audit.service.ts`,
  `apps/api-v2/src/auth/jwt.strategy.ts`,
  `apps/api-v2/src/auth/jwt.guard.ts`,
  `apps/api-v2/src/guards/auth.guard.ts`,
  `apps/api-v2/src/shared-common/csrf-protection.ts`,
  `apps/api-v2/src/shared/origin-resolver.service.ts`,
  `packages/api-types/src/http/admin-path.ts`,
  `packages/api-types/src/http/auth-cookie-policy.ts`,
  `admin-v2-pack/01-foundation-and-invariants.md`,
  `admin-v2-pack/03-platform-auth-rbac.md`,
  `admin-v2-pack/05-financial-workspaces.md`,
  `admin-v2-pack/07-backend-contracts-and-data-plan.md`,
  `admin-v2-pack/08-rollout-risks-and-sequencing.md`,
  `docs/admin-v2-mvp-2-rbac-prerequisite.md`,
  `docs/admin-v2-mvp-3-anomalies-first-slice.md`,
  `docs/admin-v2-mvp-3.1b-perf-evidence.md`,
  `docs/admin-v2-mvp-3.1c-anomaly-classes-expansion.md`,
  `docs/admin-v2-mvp-3.1c-perf-evidence.md`,
  `docs/admin-v2-mvp-3.2a-operational-assignments.md`,
  `docs/admin-v2-mvp-3.3a-saved-views-skeleton.md`,
  `docs/admin-v2-mvp-3.3b-operational-alerts-skeleton.md`,
  `packages/database-2/prisma/migrations/20260420191500_admin_v2_duplicate_idempotency_risk_index/README.md`,
  `packages/database-2/prisma/migrations/20260421100000_admin_v2_saved_views_foundation/README.md`,
  `packages/database-2/prisma/migrations/20260421100500_admin_v2_operational_alerts_foundation/README.md`,
];

export const AUDIT_ACTIONS = [
  `consumer_note_create`,
  `consumer_flag_add`,
  `consumer_flag_remove`,
  `consumer_force_logout`,
  `consumer_suspend`,
  `consumer_email_resend`,
  `verification_approve`,
  `verification_reject`,
  `payment_method_disable`,
  `payment_method_remove_default`,
  `payment_method_duplicate_escalate`,
  `payout_escalate`,
  `exchange_rate_approve`,
  `exchange_rule_pause`,
  `exchange_rule_resume`,
  `exchange_rule_run_now`,
  `exchange_scheduled_force_execute`,
  `exchange_scheduled_cancel`,
  `document_tag_create`,
  `document_tag_update`,
  `document_tag_delete`,
  `document_retag`,
  `document_bulk_tag`,
  `admin_invite`,
  `admin_deactivate`,
  `admin_restore`,
  `admin_role_change`,
  `admin_permissions_change`,
  `admin_password_reset`,
  `assignment_claim`,
  `assignment_release`,
  `assignment_reassign`,
  `saved_view_create`,
  `saved_view_update`,
  `saved_view_delete`,
  `alert_create`,
  `alert_update`,
  `alert_delete`,
];

export const CAPABILITIES = [
  `me.read`,
  `overview.read`,
  `consumers.read`,
  `consumers.notes`,
  `consumers.flags`,
  `consumers.force_logout`,
  `consumers.suspend`,
  `consumers.email_resend`,
  `verification.read`,
  `verification.decide`,
  `payments.read`,
  `ledger.read`,
  `ledger.anomalies`,
  `audit.read`,
  `exchange.read`,
  `exchange.manage`,
  `documents.read`,
  `documents.manage`,
  `admins.read`,
  `admins.manage`,
  `payment_methods.read`,
  `payment_methods.manage`,
  `payouts.escalate`,
  `system.read`,
  `assignments.manage`,
  `saved_views.manage`,
  `alerts.manage`,
];

export const FRONTEND_ACTIONS = [
  `disablePaymentMethodAction`,
  `removeDefaultPaymentMethodAction`,
  `escalateDuplicatePaymentMethodAction`,
  `approveExchangeRateAction`,
  `pauseExchangeRuleAction`,
  `resumeExchangeRuleAction`,
  `runExchangeRuleNowAction`,
  `forceExecuteScheduledExchangeAction`,
  `cancelScheduledExchangeAction`,
  `createDocumentTagAction`,
  `updateDocumentTagAction`,
  `deleteDocumentTagAction`,
  `retagDocumentAction`,
  `bulkTagDocumentsAction`,
  `inviteAdminAction`,
  `deactivateAdminAction`,
  `restoreAdminAction`,
  `changeAdminRoleAction`,
  `changeAdminPermissionsAction`,
  `resetAdminPasswordAction`,
  `claimVerificationAssignmentAction`,
  `releaseVerificationAssignmentAction`,
  `reassignVerificationAssignmentAction`,
  `createSavedViewAction`,
  `updateSavedViewAction`,
  `deleteSavedViewAction`,
  `createOperationalAlertAction`,
  `updateOperationalAlertAction`,
  `deleteOperationalAlertAction`,
];

export const ROUTE_TOKENS = {
  'apps/api-v2/src/admin-v2/admins/admin-v2-admins.controller.ts': [
    '@Post(`invite`)',
    '@Post(`:id/deactivate`)',
    '@Post(`:id/restore`)',
    '@Post(`:id/role-change`)',
    '@Post(`:id/permissions-change`)',
    '@Post(`:id/password-reset`)',
  ],
  'apps/api-v2/src/admin-v2/payment-methods/admin-v2-payment-methods.controller.ts': [
    '@Post(`:id/disable`)',
    '@Post(`:id/remove-default`)',
    '@Post(`:id/duplicate-escalate`)',
  ],
  'apps/api-v2/src/admin-v2/exchange/admin-v2-exchange.controller.ts': [
    '@Post(`rates/:id/approve`)',
    '@Post(`rules/:id/pause`)',
    '@Post(`rules/:id/resume`)',
    '@Post(`rules/:id/run-now`)',
    '@Post(`scheduled/:id/force-execute`)',
    '@Post(`scheduled/:id/cancel`)',
  ],
  'apps/api-v2/src/admin-v2/documents/admin-v2-documents.controller.ts': [
    '@Post(`tags`)',
    '@Patch(`tags/:id`)',
    '@Delete(`tags/:id`)',
    '@Post(`:id/retag`)',
    '@Post(`bulk-tag`)',
  ],
  'apps/api-v2/src/admin-v2/payouts/admin-v2-payouts.controller.ts': ['@Post(`:id/escalate`)'],
  'apps/api-v2/src/admin-v2/assignments/admin-v2-assignments.controller.ts': [
    '@Post(`claim`)',
    '@Post(`release`)',
    '@Post(`reassign`)',
  ],
  'apps/api-v2/src/admin-v2/saved-views/admin-v2-saved-views.controller.ts': [
    '@Get()',
    '@Post()',
    '@Patch(`:savedViewId`)',
    '@Delete(`:savedViewId`)',
  ],
  'apps/api-v2/src/admin-v2/operational-alerts/admin-v2-operational-alerts.controller.ts': [
    '@Get()',
    '@Post()',
    '@Patch(`:operationalAlertId`)',
    '@Delete(`:operationalAlertId`)',
  ],
};

export const ROOT_SCRIPTS = {
  'verify:admin-v2-gates': `node ./scripts/admin-v2-gates/verify.mjs`,
  'test:admin-v2': `yarn workspace @remoola/api-v2 run test --testPathPatterns='admin-v2'`,
};

export const AFFECTED_PATHS = [
  `apps/admin-v2/`,
  `apps/api-v2/src/admin-v2/`,
  `apps/api-v2/src/shared/admin-action-audit.service.ts`,
  `apps/api-v2/src/auth/jwt.strategy.ts`,
  `apps/api-v2/src/auth/jwt.guard.ts`,
  `apps/api-v2/src/guards/auth.guard.ts`,
  `apps/api-v2/src/shared-common/csrf-protection.ts`,
  `apps/api-v2/src/shared/origin-resolver.service.ts`,
  `packages/api-types/src/http/admin-path.ts`,
  `packages/api-types/src/http/auth-cookie-policy.ts`,
  `packages/database-2/prisma/schema.prisma`,
  `packages/database-2/prisma/migrations/`,
  `admin-v2-pack/01-foundation-and-invariants.md`,
  `admin-v2-pack/03-platform-auth-rbac.md`,
  `admin-v2-pack/05-financial-workspaces.md`,
  `admin-v2-pack/07-backend-contracts-and-data-plan.md`,
  `admin-v2-pack/08-rollout-risks-and-sequencing.md`,
  `docs/admin-v2-merge-gates.md`,
  `docs/admin-v2-mvp-2-rbac-prerequisite.md`,
  `docs/admin-v2-mvp-3-anomalies-first-slice.md`,
  `docs/admin-v2-mvp-3.1c-anomaly-classes-expansion.md`,
  `docs/admin-v2-mvp-3.1c-perf-evidence.md`,
  `.husky/pre-commit`,
  `package.json`,
  `scripts/admin-v2-gates/`,
];

export const OLD_DOC_TOKENS = [
  `audit-vocabulary-completeness`,
  `transaction-matrix-coverage`,
  `side-effects-map-coverage`,
  `rbac-capability-mapping-completeness`,
  `phase-control-matrix-completeness`,
  `deferred-feature-activation`,
  `nav-tier-promotion-guard`,
  `nav-audit-and-cross-link`,
  `taxonomy-completeness`,
  `sla-escalation-tuple`,
  `dead-end-case-pages`,
  `scripts/admin-v2-gates/allowlist/`,
  `allowlist.self-test.mjs`,
];

export const RECONCILIATION_NOTES = {
  'docs/admin-v2-mvp-2-rbac-prerequisite.md': [
    `schema-backed RBAC primitives уже landed`,
    `\`admins.manage\` уже используется как live capability boundary`,
    `MVP-3 maturity`,
  ],
  'admin-v2-pack/05-financial-workspaces.md': [
    `Current codebase reading`,
    `detail surface уже несет capability-gated write controls`,
  ],
  'admin-v2-pack/08-rollout-risks-and-sequencing.md': [
    `Sequence 6`,
    `ledger anomalies`,
    `current runtime already includes the writes that this kickoff slice used to exclude`,
  ],
  'docs/admin-v2-mvp-3-anomalies-first-slice.md': [
    `Sequence 6`,
    `first maturity slice`,
    `three classes`,
    `temporarily-unavailable`,
    `no new audit actions`,
    `Finding: outcome→entry sync trigger absence`,
    `Decision: largeValueOutliers currency coverage`,
    `INCONSISTENT_CHAIN_GRACE_MINUTES`,
    `11 major/reserve currencies`,
    `admin-v2-mvp-3.1b-perf-evidence.md`,
    `admin-v2-mvp-3.1c-anomaly-classes-expansion.md`,
  ],
  'docs/admin-v2-mvp-3.1b-perf-evidence.md': [
    `EXPLAIN ANALYZE`,
    `p95`,
    `summary endpoint budget`,
    `index reshape rationale`,
    `Promise.all decision`,
    `idx_ledger_entry_outcome_lateral_covering`,
    `20260420170000_admin_v2_anomalies_outcome_indexes`,
  ],
  'docs/admin-v2-mvp-3.1c-anomaly-classes-expansion.md': [
    `Sequence 6`,
    `classes expansion`,
    `six classes`,
    `temporarily-unavailable`,
    `no new audit actions`,
    `Decision: duplicateIdempotencyRisk redefinition`,
    `Decision: impossibleTransitions terminal-only scope`,
    `Decision: orphanedEntries definition`,
    `ORPHANED_ENTRY_GRACE_HOURS`,
    `TERMINAL_OUTCOME_STATUSES`,
    `admin-v2-mvp-3.1b-perf-evidence.md`,
  ],
  'docs/admin-v2-mvp-3.1c-perf-evidence.md': [
    `EXPLAIN ANALYZE`,
    `p95`,
    `summary endpoint budget`,
    `six-class summary`,
    `orphanedEntries`,
    `duplicateIdempotencyRisk`,
    `impossibleTransitions`,
    `Seq Scan justification`,
  ],
  'docs/admin-v2-mvp-3.2a-operational-assignments.md': [
    `MVP-3.2a`,
    `Sequence 6`,
    `assignments.manage`,
    `assignment_claim`,
    `assignment_release`,
    `assignment_reassign`,
    `OperationalAssignmentModel`,
    `verification only`,
    `single active assignment per resource`,
    `append-only assignment chain`,
    `no new schema migrations`,
    `Decision: resourceType allowlist verification only`,
    `Decision: capability granularity single`,
    `Decision: reassign requires SUPER_ADMIN`,
    `Decision: version check via expectedReleasedAtNull`,
  ],
  'docs/admin-v2-mvp-3.3a-saved-views-skeleton.md': [
    `MVP-3.3a`,
    `Sequence 6`,
    `saved_views.manage`,
    `saved_view_create`,
    `saved_view_update`,
    `saved_view_delete`,
    `SavedViewModel`,
    `ledger_anomalies only`,
    `personal-only ownership`,
    `soft-delete`,
    `opaque queryPayload`,
    `single workspace allowlist`,
    `Decision: workspace allowlist ledger_anomalies only`,
    `Decision: opaque queryPayload contract`,
    `Decision: personal-only ownership`,
    `Decision: soft-delete by default`,
    `Decision: name unique partial index`,
    `MAX_SAVED_VIEW_PAYLOAD_BYTES`,
    `expectedDeletedAtNull`,
  ],
  'docs/admin-v2-mvp-3.3b-operational-alerts-skeleton.md': [
    `MVP-3.3b`,
    `Sequence 7`,
    `alerts.manage`,
    `alert_create`,
    `alert_update`,
    `alert_delete`,
    `OperationalAlertModel`,
    `ledger_anomalies only`,
    `count_gt only`,
    `personal-only ownership`,
    `soft-delete`,
    `opaque queryPayload`,
    `structured thresholdPayload`,
    `single workspace allowlist`,
    `@Cron`,
    `EVALUATOR_TICK_MAX_ALERTS`,
    `EVALUATOR_PER_ALERT_TIMEOUT_MS`,
    `last_fired_at`,
    `last_evaluation_error`,
    `Decision: workspace allowlist ledger_anomalies only`,
    `Decision: separate query and threshold payloads`,
    `Decision: threshold count_gt only`,
    `Decision: in-app delivery only`,
    `Decision: no occurrence model in skeleton`,
    `Decision: no audit on fire`,
    `Decision: no confirmation on mutations`,
    `Decision: evaluation state reset on definition change`,
    `Decision: workspace immutable on update`,
    `Decision: no manual re-evaluate endpoint`,
    `Decision: workspace evaluator strategy boundary`,
    `Decision: defer link from system page`,
    `MVP-3 maturity track closed`,
    `expectedDeletedAtNull`,
    `Deviation from §1.20`,
    `getCount`,
    `AdminV2LedgerAnomaliesService.getCount`,
    `anomaly cluster read-only addition`,
    `workspace-evaluator-vs-domain-cluster boundary`,
  ],
};
